In [21]:
#Encontre índices de elementos não nulos de [1,2,0,0,4,0]

import numpy as np

matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)import numpy as np
matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)



SyntaxError: invalid syntax (<ipython-input-21-c6ab0aa57095>, line 8)

In [14]:
#Extrair a parte inteira de uma matriz aleatória
import numpy as np
matrix=np.random.rand(4,4)
import numpy as np
intmatrix=[]
for i in range(len(matrix)):
    aux=matrix[i]//1
    intmatrix.append(aux)
print(matrix)
print(intmatrix)

matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)
print(matrix2pol)

[[ 0.62684835  0.23082235  0.37046446  0.11089103]
 [ 0.72361645  0.20459109  0.53951322  0.05419972]
 [ 0.26631489  0.81271814  0.373041    0.45132473]
 [ 0.28073554  0.03560434  0.72322091  0.1181194 ]]
[array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.])]


IndexError: index 4 is out of bounds for axis 0 with size 4

In [13]:
#Considere uma matriz aleatória de 10×2 que represente coordenadas cartesianas, converta-as em coordenadas polares
import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)
print(matrix2pol)

[[ 0.07236486  0.52094267]
 [ 0.41458376  0.2360556 ]
 [ 0.61670098  0.4551709 ]
 [ 0.67566593  0.51473841]
 [ 0.93685748  0.92802058]
 [ 0.38923614  0.73998761]
 [ 0.31625706  0.6035091 ]
 [ 0.68714673  0.34868541]
 [ 0.61677857  0.9882361 ]
 [ 0.50463865  0.78873551]]
[(0.52594480157944112, 1.4327682414160059), (0.47707644692750734, 0.51760026151913685), (0.76648591044070458, 0.63582460977987387), (0.8493998372747309, 0.65102551707300393), (1.3186827280399103, 0.78065960057253936), (0.8361138939449867, 1.0865629077410508), (0.68135288506649694, 1.0881098017087287), (0.77055313940853731, 0.46958149706580499), (1.1649147594894578, 1.012829591043356), (0.93635669598558557, 1.001619932939404)]


In [23]:
#Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos


import numpy as np

matrix=np.random.rand(100,2)
matrixD=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixD.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print matrixD

In [35]:
#Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?

import numpy as np
vetor=[1,2,3,4,5]
vetor2=[]
for i in range(len(vetor)):
    vetor2.append(vetor[i])
    for i in range(0,3):
        vetor2.append(0)
print(vetor2)



[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]


In [1]:
#Exercicio do Jogo da Vida

            for i in r for j in r # iterate over range in 2d
            if not i == j == 0) # exclude the center cell


def advance(board):
    """Advance the board one step and return it."""
    new_board = set()
    for cell in board:
        cell_neighbors = set(neighbors(cell))
        # test if live cell dies
        if len(board & cell_neighbors) in [2, 3]:
            new_board.add(cell)

 return new_board


def print_board(board, size=None):
    sizex = sizey = size or 0
    for x, y in board:
        sizex = x if x > sizex else sizex
        sizey = y if y > sizey else sizey
    for i in xrange(sizex + 1):
        for j in xrange(sizey + 1):
            sys.stdout.write(' x ' if (i, j) in board else ' . ')
        print


def constrain(board, size):
    return set(cell for cell in board if cell[0] <= size and cell[1] <= size)


def main(board, steps=75, size=20):
    for i in xrange(1, steps + 1):
        sys.stdout.write('\033[H')  # move to the top
        sys.stdout.write('\033[J')  # clear the screen
        print 'step:', i, '/', steps
        print_board(board, size)
        time.sleep(0.1)
        board = constrain(advance(board), size)


if __name__ == '__main__':
    main(GLIDER)



IndentationError: unexpected indent (<ipython-input-1-c58b3d6c991b>, line 3)