# Exercícios para fazer na aula
Encontre índices de elementos não nulos de [1,2,0,0,4,0]


### Exercício 1

In [3]:
m = [1,2,0,0,4,0]
v = []
for i in range (len(m)-1):
  if m[i] != 0:
    v.append(i)
print (v)


[0, 1, 4]


### Exercício 2

In [10]:
import numpy as np
m = np.random.rand(3,4)
print m

x = m.astype(int)
print ("Os valores inteiros da matriz acima sao: ")
print x




[[ 0.01953752  0.92900571  0.72934263  0.54655129]
 [ 0.85603919  0.23016439  0.78519469  0.24678352]
 [ 0.91674096  0.59234787  0.48635739  0.442139  ]]
Os valores inteiros da matriz acima sao: 
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### Exercício 3

In [1]:
import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)        
print(matrix2pol)

[[ 0.44158837  0.24501626]
 [ 0.57445655  0.83270878]
 [ 0.64415414  0.41603037]
 [ 0.22822209  0.36149107]
 [ 0.12578158  0.17332164]
 [ 0.1276567   0.86333554]
 [ 0.47500183  0.93781487]
 [ 0.93638461  0.81523578]
 [ 0.3523522   0.83926065]
 [ 0.16996951  0.72239271]]
[(0.50500817375366902, 0.50656083298939725), (1.0116344405767226, 0.96690488146320575), (0.7668218990741783, 0.5734560283806085), (0.42750569109334441, 1.0076542356028158), (0.21415274454081659, 0.94302164807653965), (0.87272245761005518, 1.4239955093489685), (1.0512485257777406, 1.1019634365757394), (1.2415415864032708, 0.71634426983988631), (0.91022552444266447, 1.1733073824269618), (0.74211916791866472, 1.3397125405087162)]


### Exercício 4

In [5]:
import numpy as np

matrix=np.random.rand(10,2)
matrixD=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixD.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print matrixD

[0.063810954623529259, 0.40546311584469424, 0.37112106819598223, 0.50801531383592335, 0.18994140176905053, 0.29817662461455952, 0.24656420562368328, 0.23787078611806506, 0.32116215761693395, 0.42636874641426276, 0.23070633105838823, 0.16529286714711433, 0.64194717096787079, 0.5712044542174437, 0.082221348949110082, 0.4481735154927563, 0.51692487230006279, 0.4431101997899467, 0.11884938537551273, 0.66033350719796091, 0.38664957933978011, 0.73647211646977884, 0.043758997900735674, 0.61621986641532078, 0.52867523216701551, 0.39486148617673333, 0.099149076245345316, 0.29808564663709186, 0.64893823658309446, 0.26663471783016779, 0.47498060320364188, 0.17459512133601507, 0.88832171326105569, 0.71830189417521317, 0.3283885770954002, 0.65597307248236081, 0.76321026696923933, 0.67161066918641532, 0.24689123682829914, 0.89150542616090533, 0.14240564711831596, 0.23864367711252502, 0.55088805162376941, 0.5356589061615622, 0.013454162165316808, 0.38316239165305849, 0.42593860819647827, 0.3646298392

### Exercício 5

In [6]:
vetor=[0,1,2,3,4,5]
vetor2=[]
for i in range(len(vetor)):
    vetor2.append(vetor[i])
    for i in range(0,3):
        vetor2.append(0)
print(vetor2)

[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
