# Numpy

Numpy é a biblioteca essencial para computação científica em Python. Ela fornece um objeto que é essencialmente uma
_array_ multidimensional e métodos de  alto desempenho para trabalhar com esses _arrays_. 

## Arrays
- Uma matriz numpy é uma tabela de valores, todos do mesmo tipo, e é indexada por uma tupla de inteiros não negativos.
- O número de dimensões é o grau da matriz.
- A forma de uma matriz é uma tupla de inteiros que dão o tamanho da matriz ao longo de cada dimensão.
- Podemos inicializar matrizes numpy de listas concatenadas de Python e acessar elementos usando colchetes:

In [2]:
import numpy as np

In [3]:
a= [[1,2,3,9], [6,5,4,20],[2,4,5,7]]
matriz = np.array(a)
matriz


array([[ 1,  2,  3,  9],
       [ 6,  5,  4, 20],
       [ 2,  4,  5,  7]])

In [4]:
type(matriz)
type(a)

list

In [5]:
matriz1 = np.array(a, float)
matriz1

array([[  1.,   2.,   3.,   9.],
       [  6.,   5.,   4.,  20.],
       [  2.,   4.,   5.,   7.]])

- Podemos verificar o número de linhas e colunas em nossos dados usando a propriedade `shape` de _arrays_ NumPy:

In [6]:
matriz.shape

(3, 4)

Para criar um vetor linha fazemos:


In [39]:
vetor_linha=np.array([[1,2,3]]) # cria um vetor linha

Para criar um vetor coluna temos que fazer:


In [40]:
vetor_coluna=np.array([[1],[2],[3]])

In [41]:
vetor_coluna

array([[1],
       [2],
       [3]])

In [42]:
vetor_coluna.T

array([[1, 2, 3]])

In [43]:
vetor_linha.T

array([[1],
       [2],
       [3]])

In [44]:
vetor_linha*vetor_coluna

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

### Matriz com zeros

- Para começar, você pode criar uma matriz onde cada elemento é zero. O código a seguir criará uma matriz com 3 linhas e 4 colunas, onde cada elemento é 0 , usando `np.zeros`:

In [24]:
empty_array = np.zeros((3,4))
empty_array

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

- É útil criar uma matriz com todos os elementos zero nos casos em que você precisa de uma matriz de tamanho fixo, mas ainda não tem nenhum valor para ela.

### Matriz de números aleatórios (Random)
- É possível criar uma matriz onde cada elemento é um número aleatório usando `numpy.random.rand`. Veja o exemplo a seguir: 

In [8]:
np.random.rand(3,4)

array([[ 0.3321051 ,  0.6748329 ,  0.27149443,  0.39591691],
       [ 0.08844625,  0.77155174,  0.46242975,  0.05445745],
       [ 0.30244142,  0.23781445,  0.88637903,  0.90571926]])

### Criando matriz com Reshape

In [9]:
x = np.array(range(12)).reshape(3,4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Índices e fatias
- Para acessar um elemento de uma lista de dimensão n é necessário fornecer o valor de n índices, ou seja, 2 índices para uma matriz bidimensional, 3 índices para uma matriz tridimensional e assim por diante.
- Embora seja possível usar a mesma forma para acessar elementos de um array, uma forma mais eficiente é separando os valores por vírgulas, como a seguir:

In [10]:
lista = [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]
lista

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

In [11]:
lista[0:-1]

[[0, 1, 2, 3], [4, 5, 6, 7]]

In [12]:
mat = np.array(lista)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
mat[1:-1] ##Pegando penúltima linha

array([[4, 5, 6, 7]])

In [31]:
mat[:,2]## Pegando a terceira coluna

array([ 2,  6, 10])

In [32]:
mat[:,2:]## Duas ultimas colunas e linhas

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

### Operações com arrays
- O NumPy oferece muito mais recursos que listas para operação e manipulação de arrays que facilitam a computação científica.

In [35]:
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[0,2],[3,1]])
soma=a1+b1
multiplicacao=a1*b1
subtracao=b1/a1
print('Soma:',soma)
print('Multiplicação:',soma)
print('Subtração:',soma)

Soma: [[1 4]
 [6 5]]
Multiplicação: [[1 4]
 [6 5]]
Subtração: [[1 4]
 [6 5]]


In [45]:
a=np.array([[1,2,3]])
np.dot(a,a.T)

array([[14]])

### Operações entre arrays de tamanhos distintos
- Em muitos casos, é necessário trabalhar com arrays com um número distinto de elementos, ou de formas diferentes. Nesse caso, é necessário entender as regras do NumPy que difundem as informações do array menor para o array maior.
- O termo difusão (broadcasting) descreve como NumPy trata arrays de dimensões diferentes em operações aritméticas. O array menor é “difundido” a uma array maior para que tenham as mesmas dimensões. No caso de um escalar, o valor do escalar é difundido para todos os elementos do array maior, como no exemplo:

In [36]:
a2 = np.array([[1,2],[3,4]])
a2 + 1

array([[2, 3],
       [4, 5]])

In [39]:
a2 * 2

array([[2, 4],
       [6, 8]])

In [40]:
a2/2

array([[ 0.5,  1. ],
       [ 1.5,  2. ]])

### Atribuir valores a NumPy Arrays
- Também podemos usar a indexação para atribuir valores a determinados elementos em arrays. Podemos fazer isso atribuindo diretamente ao valor indexado:

In [14]:
numeros=np.random.rand(3,4)
numeros[ 1 , 2] = 10
numeros [:, 2 ] = 50

In [15]:
numeros

array([[  1.90657252e-02,   4.28180493e-01,   5.00000000e+01,
          9.06423263e-02],
       [  7.35581466e-01,   5.10557350e-01,   5.00000000e+01,
          3.05358515e-01],
       [  9.57031620e-02,   4.72088543e-01,   5.00000000e+01,
          9.70031312e-01]])

### Tipos de dados NumPy
-  NumPy armazena valores usando seus próprios tipos de dados, que são distintos de tipos Python como **float** e **str** . Isso ocorre porque o núcleo do NumPy é escrito em uma linguagem de programação chamada C, que armazena dados de forma diferente dos tipos de dados Python. Os tipos de dados NumPy mapeiam entre Python e C, permitindo-nos usar matrizes NumPy sem nenhum engate de conversão.
- Você pode encontrar o tipo de dados de uma matriz NumPy acessando a propriedade dtype:

In [16]:
numeros.dtype

dtype('float64')

- NumPy tem vários tipos de dados diferentes, que mapeiam principalmente para tipos de dados Python, como float e str . Você pode encontrar uma lista completa dos tipos de dados NumPy aqui , mas aqui estão alguns importantes:

- **float** - dados numéricos de ponto flutuante.
- **int** - dados inteiros.
- **string** - dados de caracteres.
- **object** - Objetos Python.
 
- Os tipos de dados, adicionalmente, terminam com um sufixo que indica quantos bits de memória eles ocupam. Assim, int32 é um tipo de dados inteiros de 32 bits e float64 é um tipo de dados float de 64 bits.

### Convertendo tipos de dados
- Você pode usar o método **numpy.ndarray.astype** para converter uma matriz em um tipo diferente. O método realmente copiará a matriz e retornará uma nova matriz com o tipo de dados especificado. 

In [17]:
numeros.astype(int)

array([[ 0,  0, 50,  0],
       [ 0,  0, 50,  0],
       [ 0,  0, 50,  0]])

### NumPy Array Comparações
- NumPy torna possível testar para ver se as linhas correspondem a certos valores usando operações de comparação matemática como < , > , >= , <= e == . Por exemplo, se queremos ver quais vinhos têm uma classificação de qualidade superior a 5 , podemos fazer o seguinte:

In [18]:
numeros

array([[  1.90657252e-02,   4.28180493e-01,   5.00000000e+01,
          9.06423263e-02],
       [  7.35581466e-01,   5.10557350e-01,   5.00000000e+01,
          3.05358515e-01],
       [  9.57031620e-02,   4.72088543e-01,   5.00000000e+01,
          9.70031312e-01]])

In [19]:
numeros> 5

array([[False, False,  True, False],
       [False, False,  True, False],
       [False, False,  True, False]], dtype=bool)

In [20]:
numeros[:, 0 ] == 10

array([False, False, False], dtype=bool)

In [21]:
numeros[:, 2] == 50.

array([ True,  True,  True], dtype=bool)

### Subsetting
- Uma das operações poderosas que podemos realizar com uma matriz booleana e uma matriz NumPy é selecionar apenas algumas linhas ou colunas na matriz NumPy. Por exemplo, o código abaixo só irá selecionar linhas cuja qualidade é superior a 7 :

In [22]:
high_quality = numeros[:,1] > 2
numeros[high_quality,:][:3,:]

array([], shape=(0, 4), dtype=float64)

## Operações Diversas

- Para achatar os dados, ou seja acabar com sua estrutura interna

In [23]:
numeros.ravel()

array([  1.90657252e-02,   4.28180493e-01,   5.00000000e+01,
         9.06423263e-02,   7.35581466e-01,   5.10557350e-01,
         5.00000000e+01,   3.05358515e-01,   9.57031620e-02,
         4.72088543e-01,   5.00000000e+01,   9.70031312e-01])

Para inserir uma linha em um `array`:

In [30]:
np.vstack((numeros, [1,2,3,4]))

array([[  1.90657252e-02,   4.28180493e-01,   5.00000000e+01,
          9.06423263e-02],
       [  7.35581466e-01,   5.10557350e-01,   5.00000000e+01,
          3.05358515e-01],
       [  9.57031620e-02,   4.72088543e-01,   5.00000000e+01,
          9.70031312e-01],
       [  1.00000000e+00,   2.00000000e+00,   3.00000000e+00,
          4.00000000e+00]])

Para inserir uma coluna. Note que temos que criar um vetor coluna.


In [31]:
np.hstack((numeros,[[1],[2],[3]]))

array([[  1.90657252e-02,   4.28180493e-01,   5.00000000e+01,
          9.06423263e-02,   1.00000000e+00],
       [  7.35581466e-01,   5.10557350e-01,   5.00000000e+01,
          3.05358515e-01,   2.00000000e+00],
       [  9.57031620e-02,   4.72088543e-01,   5.00000000e+01,
          9.70031312e-01,   3.00000000e+00]])

## Álgebra Linear

In [46]:

from numpy import linalg as LA
arr2d = np.array((  (100,200,300), 
          (111,222,333), 
          (129,461,795) ))



Calcula os autovalores:

In [47]:
eig_val, eig_vec = LA.eig(arr2d)

In [48]:
eig_val

array([  1.05664180e+03,   6.03582029e+01,   2.37768608e-14])

In [49]:
eig_vec

array([[ 0.34860455,  0.57805139,  0.41356846],
       [ 0.38695105,  0.64163704, -0.81514943],
       [ 0.8536649 , -0.50414135,  0.4055768 ]])

In [51]:
LA.norm(arr2d) # calcula a norma da matriz


1083.3655892633844

In [0]:
LA.det(arr2d) # calcula determinante


In [0]:
LA.inv(arr2d) # calcula inversa

Resolve sistemas lineares na forma

$$ a x + b y = c $$
$$ d x + e y = f $$

$$\left(\begin{array} 
 a a & b \\
d & e 
\end{array}\right)\cdot
\left(
\begin{array}
x x \\
y
\end{array}
\right)=
\left(
\begin{array}
c c \\
f
\end{array}
\right)
$$

In [0]:
arr1 = np.array([[2,3], [3,4]])
arr2 = np.array([4,5])
results = np.linalg.solve(arr1, arr2)
print results

## Exercícios para fazer na aula
- Encontre índices de elementos não nulos de [1,2,0,0,4,0] 
- Extrair a parte inteira de uma matriz aleatória
- Considere uma matriz aleatória de 10$\times$2 que represente coordenadas cartesianas, converta-as em coordenadas polares
- Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as  distâncias entre todos os pontos 
- Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?

### Exercício 1 - Jogo da Vida (0.25)
- O Jogo da Vida (The Game of Life) é um autômato celular (cellular automaton) introduzido por John Horton Conway em 1970. Um automato celular consiste de uma rede de células. Cada célula pode estar em um número finito de estados, como morta ou viva. O “jogo” é na verdade uma simulação que permite observar a evolução de um processo a partir de uma certa condição inicial.
- O jogo se desenvolve sobre uma matriz bi-dimensional que pode ser tão grande quanto se queira. Vamos chamar essa matriz de mapa. Cada posição ou célula do mapa pode estar vazia (= célula morta) ou ocupada por um agente (= célula viva). Cada posição possui também até 8 posições vizinhas: imediatamente acima, abaixo, aos lados e nas diagonais. Em um determinado instante, o mapa contém uma geração de agentes. A geração no instante seguinte é determinada segundo as regras abaixo:
- Novos agentes nascem em células vazias que possuam exatamente 3 agentes vizinhos;
- **Agentes com 2 ou 3 agentes vizinhos sobrevivem;**
- **Agentes com menos de 2 agentes vizinhos morrem for falta de recursos;**
- **Agentes com mais de 3 agentes vizinhos morrem por excesso de competição.**