In [1]:
#EX1
import numpy as np
matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)

0
1
4


In [2]:
#EX2
import numpy as np
matrix=np.random.rand(3,4)
intmatrix=[]
for i in range(len(matrix)):
    aux=matrix[i]//1
    intmatrix.append(aux)
print(matrix)
print(intmatrix)

[[ 0.65748911  0.46765986  0.59014281  0.76557238]
 [ 0.19081901  0.98503946  0.60931284  0.6573868 ]
 [ 0.74161526  0.56555606  0.21314921  0.89606957]]
[array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.])]


In [3]:
#EX3
import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)        
print(matrix2pol)

[[ 0.09617462  0.87681929]
 [ 0.57630831  0.7645858 ]
 [ 0.36744914  0.74210815]
 [ 0.58711779  0.74147866]
 [ 0.15810675  0.47750131]
 [ 0.29537648  0.88740552]
 [ 0.86839214  0.05182819]
 [ 0.38836671  0.74323155]
 [ 0.1518905   0.31167687]
 [ 0.22380335  0.57876857]]
[(0.88207800981659057, 1.4615472650081784), (0.95745637256489458, 0.92489806526812612), (0.82809624006927141, 1.1110424213492647), (0.94577898827311213, 0.90106300104589843), (0.5029962732651504, 1.2510456622129398), (0.9352731229031388, 1.2494772282294877), (0.869937398698577, 0.059612223571814317), (0.83858323602175655, 1.0892813328296556), (0.34671774889381601, 1.1173333696955274), (0.62053283432614237, 1.2018174874147154)]


In [7]:
#EX4
import numpy as np

matrix=np.random.rand(100,2)
matrixdis=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixdis.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print (matrixdis)

In [8]:
#EX 5
vetor=[0,1,2,3,4,5]
vetor1=[]
for i in range(len(vetor)):
    vetor1.append(vetor[i])
    for i in range(0,3):
        vetor1.append(0)
print(vetor1)

[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
