In [1]:
#Ex1
import numpy as np
matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)

0
1
4


In [2]:
#Ex2
import numpy as np
matrix=np.random.rand(3,4)
intmatrix=[]
for i in range(len(matrix)):
    aux=matrix[i]//1
    intmatrix.append(aux)
print(matrix)
print(intmatrix)

[[ 0.94980738  0.56677557  0.80197662  0.25411207]
 [ 0.14332811  0.58775354  0.5401163   0.8739897 ]
 [ 0.77308489  0.51691692  0.42936502  0.76837351]]
[array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.])]


In [3]:
#Ex3
import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)        
print(matrix2pol)

[[ 0.86927144  0.61938292]
 [ 0.49178568  0.98133734]
 [ 0.56027295  0.09604583]
 [ 0.73963993  0.95737984]
 [ 0.06129318  0.63744269]
 [ 0.54021657  0.87333502]
 [ 0.18470434  0.20475036]
 [ 0.86462455  0.55633293]
 [ 0.52705262  0.73643653]
 [ 0.80223956  0.41878286]]
[(1.0673649990903926, 0.61908667156796671), (1.0976684999513755, 1.1062385304120927), (0.56844575649018403, 0.16977660375220935), (1.2098112965707835, 0.91300817298094672), (0.64038273079127672, 1.4749362296457127), (1.0269118802419315, 1.016836083263259), (0.2757506166020311, 0.83682479191297077), (1.0281449055255019, 0.57174889408985596), (0.90560655649528243, 0.94962445447408472), (0.90496816892957199, 0.48110583538700796)]


In [4]:
#Ex4
import numpy as np

matrix=np.random.rand(10,2)
matrixD=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixD.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print matrixD

[0.47565054882305047, 0.94528323035751904, 1.0824670390934221, 0.97649864368375072, 0.46235966735065775, 0.95795357438675488, 0.21118571335813274, 0.79243315491454613, 0.6292075981911901, 0.63358970072856913, 0.6530989230214741, 0.067736781385336786, 0.19908274717532148, 0.21259061593125028, 0.43454206000915052, 0.32439284509937055, 0.71390741473981378, 0.49807592146550583, 0.41373314348135626, 0.57145650143665783, 0.7463570103399636, 0.075641810075630089, 0.10904052635838901, 0.20982375593440561, 0.5409104207945663, 0.33978475812531556, 0.81952563826728408, 0.55649018310805975, 0.50120247741086854, 0.65145233752475784, 0.53357649740430657, 0.19934811802958671, 0.33806697721552637, 0.28895588541303363, 0.28912026964105908, 0.35769787414222032, 0.56992043539290871, 0.44778505458243406, 0.31368611751694375, 0.47899680803798966, 0.36576730373205496, 0.4664491465569936, 0.60456885407602157, 0.51689512013030992, 0.025568202148837149, 0.53168217687406027, 0.30656258558231403, 0.4740188933576

In [5]:
#Ex5
vetor=[0,1,2,3,4,5]
vetor2=[]
for i in range(len(vetor)):
    vetor2.append(vetor[i])
    for i in range(0,3):
        vetor2.append(0)
print(vetor2)

[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
