## Exercícios para fazer na aula
- Encontre índices de elementos não nulos de [1,2,0,0,4,0] 
- Extrair a parte inteira de uma matriz aleatória
- Considere uma matriz aleatória de 10$\times$2 que represente coordenadas cartesianas, converta-as em coordenadas polares
- Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as  distâncias entre todos os pontos 
- Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?

## **EXERCÍCIO 1**

In [18]:
import numpy as np
a = np . array([[1,2,0,0,4,0]])
a

array([[1, 2, 0, 0, 4, 0]])

In [19]:
ab=np.nonzero(a)
ab

(array([0, 0, 0]), array([0, 1, 4]))

In [20]:
a=ab[1:2]
a

(array([0, 1, 4]),)

## **EXERCÍCIO 2**

In [17]:
import numpy as np
matrizal=np.random.uniform(1,8,10)
matrizal

array([ 4.08323689,  4.3035512 ,  1.98868513,  6.93012432,  6.46150941,
        4.94478717,  4.73650367,  1.97051585,  2.45858961,  5.2941766 ])

In [18]:
a=np.floor(matrizal)
a

array([ 4.,  4.,  1.,  6.,  6.,  4.,  4.,  1.,  2.,  5.])

In [21]:
s=np.random.uniform(-1,0,1000)
s

array([-0.38138742, -0.55831585, -0.52644807, -0.53439092, -0.72040794,
       -0.83535408, -0.94267339, -0.61470982, -0.39326432, -0.11915962,
       -0.35247004, -0.79130984, -0.84549565, -0.69027871, -0.38698136,
       -0.54864664, -0.97156494, -0.97136929, -0.4027182 , -0.67117915,
       -0.46157207, -0.17220847, -0.96409014, -0.5475501 , -0.1013316 ,
       -0.24083462, -0.45367189, -0.43376226, -0.53600399, -0.59891471,
       -0.59109139, -0.21582327, -0.67848201, -0.33139358, -0.18269097,
       -0.26594537, -0.41990113, -0.66498615, -0.79211274, -0.52099184,
       -0.76783645, -0.84515025, -0.77961309, -0.73826766, -0.32714256,
       -0.61981074, -0.59566931, -0.1234886 , -0.55102462, -0.17470882,
       -0.55916433, -0.49036947, -0.50090793, -0.05525166, -0.15082657,
       -0.60247735, -0.80811961, -0.64176127, -0.26046203, -0.38518825,
       -0.99640938, -0.43160802, -0.17691812, -0.30511151, -0.27672873,
       -0.10661581, -0.66246171, -0.26907049, -0.66092412, -0.66

## **EXERCÍCIO 3**

In [8]:
import numpy as np
matt=np.random.rand(10,2)
print 'matriz aleatoria:\n', matt
    
def cart2pol(x,y):
    rho = np.sqrt(x*2 + y*2)
    phi = np.arctan2(y, x)
    return [rho, phi]
lista=[]
for elem in matt:
    lista=lista+[cart2pol(elem[0],elem[1])]

matriz aleatoria:
[[  3.14342755e-01   3.12315046e-01]
 [  2.63249551e-01   9.49171294e-01]
 [  1.11615472e-02   9.65239288e-01]
 [  1.98587423e-01   9.63846443e-01]
 [  3.84051304e-01   4.16602490e-01]
 [  9.45460125e-01   5.44641008e-01]
 [  4.06406836e-01   8.35218586e-02]
 [  4.22111496e-01   5.67388955e-01]
 [  6.13465008e-01   2.46702157e-04]
 [  1.94617480e-01   8.45323727e-01]]


## **EXERCÍCIO 4**

In [12]:
import numpy as np
from numpy import linalg as LA

coord=np.random.rand(100,2)
coord

array([[ 0.19461849,  0.661261  ],
       [ 0.73412607,  0.98318118],
       [ 0.75867157,  0.2388484 ],
       [ 0.35972046,  0.26946497],
       [ 0.63481106,  0.78773099],
       [ 0.67779735,  0.30700325],
       [ 0.09772033,  0.26157364],
       [ 0.21331205,  0.07373196],
       [ 0.98730932,  0.70941553],
       [ 0.94436295,  0.93754173],
       [ 0.15517689,  0.31504849],
       [ 0.61793604,  0.54011653],
       [ 0.96310208,  0.27254886],
       [ 0.01582284,  0.74377567],
       [ 0.11477567,  0.33153495],
       [ 0.67521825,  0.91682125],
       [ 0.52311887,  0.95005891],
       [ 0.55495307,  0.31994901],
       [ 0.95963798,  0.26349418],
       [ 0.37317231,  0.50343044],
       [ 0.11246787,  0.20897211],
       [ 0.49457344,  0.05198558],
       [ 0.06566275,  0.49561232],
       [ 0.82825904,  0.17168774],
       [ 0.34654291,  0.89028478],
       [ 0.06883196,  0.97845851],
       [ 0.72549714,  0.50579463],
       [ 0.31931096,  0.97278505],
       [ 0.99024216,

In [22]:
[np.array([[(LA.norm(x-y)-coord)**(0.5)]])]
print 'distancia entre os pontos:\n' , [LA.norm(coord[i+1]-coord[i])for i in range(99)]

NameError: name 'x' is not defined

## **EXERCÍCIO 5**

In [14]:
import numpy as np
vetor_linha=np.array([1,2,3,4,5]) 
v1=np.zeros(3)
intercalado=np.ravel([np.append(vetor_linha[elem],v1)for elem in range(5)])
print 'O vetor', vetor_linha, 'com 3 zeros consecutivos em cada vetor é:', intercalado

O vetor [1 2 3 4 5] com 3 zeros consecutivos em cada vetor é: [ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.  0.
  0.  0.]


## **JOGO DA VIDA**

In [23]:
import numpy as np

def iterate_1(Z):
    # Contagem vizinhança
    N = np.zeros(Z.shape, int)
    N[1:-1,1:-1] += (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
                     Z[1:-1,0:-2]                + Z[1:-1,2:] +
                     Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    N_ = N.ravel()
    Z_ = Z.ravel()

    # Aplicação das regras
    R1 = np.argwhere( (Z_==1) & (N_ < 2) )
    R2 = np.argwhere( (Z_==1) & (N_ > 3) )
    R3 = np.argwhere( (Z_==1) & ((N_==2) | (N_==3)) )
    R4 = np.argwhere( (Z_==0) & (N_==3) )

    # Definir novos valores
    Z_[R1] = 0
    Z_[R2] = 0
    Z_[R3] = Z_[R3]
    Z_[R4] = 1

    # Garantia de que as fronteiras permaneçam nulas
    Z[0,:] = Z[-1,:] = Z[:,0] = Z[:,-1] = 0


def iterate_2(Z):
    # Contagem vizinhança
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Aplicação das regras
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z


Z = np.array([[0,0,0,0,0,0],
              [0,0,0,1,0,0],
              [0,1,0,1,0,0],
              [0,0,1,1,0,0],
              [0,0,0,0,0,0],
              [0,0,0,0,0,0]])

print Z
print
for i in range(4): iterate_2(Z)
print Z

[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 1 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]]


In [2]:
import matplotlib.pyplot as plt
import numpy as np

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z


#grafico
Z = np.random.randint(0,2,(256,512))
for i in range(100): iterate(Z)
size = np.array(Z.shape)
dpi = 72.0
figsize= size[1]/float(dpi),size[0]/float(dpi)
fig = plt.figure(figsize=figsize, dpi=dpi, facecolor="white")
fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon=False)
plt.imshow(Z,interpolation='nearest', cmap=plt.cm.gray_r)
plt.xticks([]), plt.yticks([])
plt.show()