In [1]:
#Exercício 1

import numpy as np
matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)

0
1
4


In [2]:
#Exercício 2

import numpy as np
matrix=np.random.rand(3,4)
intmatrix=[]
for i in range(len(matrix)):
    aux=matrix[i]//1
    intmatrix.append(aux)
print(matrix)
print(intmatrix)

[[ 0.3995668   0.47192417  0.19802905  0.12809977]
 [ 0.634226    0.98492364  0.7930589   0.64551253]
 [ 0.72003793  0.31154016  0.77761613  0.29558676]]
[array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.])]


In [3]:
#Exercício 3

import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)        
print(matrix2pol)

[[ 0.98132201  0.89989813]
 [ 0.60080656  0.19346379]
 [ 0.04958506  0.76985912]
 [ 0.10426923  0.85968268]
 [ 0.08672395  0.95207269]
 [ 0.97753925  0.79473516]
 [ 0.97026864  0.95150408]
 [ 0.58899454  0.89371562]
 [ 0.98997494  0.27185801]
 [ 0.62515001  0.49630393]]
[(1.3314689378590541, 0.74214267287029423), (0.63118678446278298, 0.31152226432265417), (0.7714543081493771, 1.5064771969752286), (0.86598290109988041, 1.4500978331653289), (0.95601435205403718, 1.4799573861876079), (1.2598360851508417, 0.68261504178484922), (1.3589633000410166, 0.77563428287102743), (1.0703467538675342, 0.98809216772232356), (1.0266241546171642, 0.2680045247893727), (0.79820431902695377, 0.67100773329468577)]


In [6]:
#Exercício 4

matrix=np.random.rand(100,2)
matrixD=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixD.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print matrixD

[0.24301655254561838, 0.49513325227637239, 0.28777653531124858, 0.58741126249736197, 0.9396681174767364, 0.74311907682681444, 0.66544050209145889, 0.552045524230524, 0.55821489409100256, 0.55786765680129125, 0.15500827933456124, 0.68272240045911248, 0.63910041611725454, 0.59366276651531147, 0.5895125269183531, 0.77867642073165499, 0.82100243472795564, 0.47126356224040289, 0.78612858054224766, 0.62671325895059871, 0.82807101205331934, 0.6199014338023392, 0.72520797900043832, 0.49309115600115072, 0.69094314934718937, 0.61539026769123328, 0.53775439784465684, 0.88532474897467439, 0.24586289360131633, 0.47654352215751078, 0.4966831683556388, 0.28130101782923794, 0.76396488551824471, 0.35311934440397114, 0.53961909207778347, 0.8201146597033514, 0.76011370386459287, 0.20823537394433925, 0.58906637846518872, 0.63839960872901225, 0.45720603529446507, 0.91167355763058044, 0.22704898417793587, 0.14439563241646591, 0.58652459131928336, 0.64124868817914915, 0.59226663912033772, 0.19906920677216869

In [5]:
#Exercício 5

vetor=[0,1,2,3,4,5]
vetor2=[]
for i in range(len(vetor)):
    vetor2.append(vetor[i])
    for i in range(0,3):
        vetor2.append(0)
print(vetor2)

[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
