## Exercício 1

In [1]:
import random

lista = []
intervalo_media=[]
for i in range(100):
  lista.append(random.randint(0, 1000))
print lista
print 

for i in range(len(lista)-1):
  intervalo_media.append((lista[i] + lista[i+1])/2)
print intervalo_media  


[731, 84, 297, 659, 309, 434, 618, 546, 59, 332, 500, 752, 762, 892, 599, 58, 283, 639, 618, 675, 494, 115, 303, 727, 267, 575, 960, 236, 321, 644, 113, 952, 751, 213, 498, 561, 794, 207, 761, 429, 70, 782, 761, 592, 336, 23, 389, 714, 223, 151, 12, 434, 652, 682, 530, 569, 310, 866, 945, 702, 994, 130, 193, 272, 599, 562, 918, 170, 602, 128, 111, 627, 957, 662, 411, 662, 291, 436, 990, 255, 120, 319, 100, 309, 993, 407, 37, 850, 477, 473, 818, 758, 29, 142, 526, 403, 278, 707, 260, 341]

[407, 190, 478, 484, 371, 526, 582, 302, 195, 416, 626, 757, 827, 745, 328, 170, 461, 628, 646, 584, 304, 209, 515, 497, 421, 767, 598, 278, 482, 378, 532, 851, 482, 355, 529, 677, 500, 484, 595, 249, 426, 771, 676, 464, 179, 206, 551, 468, 187, 81, 223, 543, 667, 606, 549, 439, 588, 905, 823, 848, 562, 161, 232, 435, 580, 740, 544, 386, 365, 119, 369, 792, 809, 536, 536, 476, 363, 713, 622, 187, 219, 209, 204, 651, 700, 222, 443, 663, 475, 645, 788, 393, 85, 334, 464, 340, 492, 483, 300]


## Exercício 3

In [4]:
import math

a = float(input("Insira o valor de A: "))
b = float(input("Insira o valor de B: "))
c = float(input("Insira o valor de C: "))
delta = math.pow(b,2) - 4*a*c
print("O Delta vale: "+str(delta))
if delta>0:
    x1 = (-b + math.sqrt(delta))/float(2*a)
    x2 = (-b - math.sqrt(delta))/float(2*a)
    print("Existem duas raizes reais"+str(x1)+"e"+str(x2))


Digite um valor para A:  2

Digite um valor para B:  6

Digite um valor para C:  3

O Delta vale: -8.0


## Exercício 6

In [6]:
import random
import pandas as pd
import numpy as np
nomes= ["Lucas", "Gustavo", "Felipe", "Gabriel", "Juan"]
notas = []
for i in range(5):
    a = []
    for j in range(10):
        a.append(random.randint(0,10))
    notas.append(a)
for i in range(5):
    print("As notas do "+str(nomes[i])+" são "+str(notas[i]))
notas = np.array(notas)
print(notas)




As notas do Lucas são [7, 5, 5, 3, 0, 7, 5, 5, 3, 8]
As notas do Gustavo são [8, 9, 7, 3, 7, 1, 6, 9, 1, 8]
As notas do Felipe são [2, 4, 8, 4, 9, 9, 10, 9, 3, 10]
As notas do Gabriel são [7, 6, 1, 8, 5, 2, 2, 2, 8, 0]
As notas do Juan são [2, 6, 10, 0, 0, 6, 9, 4, 0, 6]
[[ 7  5  5  3  0  7  5  5  3  8]
 [ 8  9  7  3  7  1  6  9  1  8]
 [ 2  4  8  4  9  9 10  9  3 10]
 [ 7  6  1  8  5  2  2  2  8  0]
 [ 2  6 10  0  0  6  9  4  0  6]]


## Exercício 4

In [8]:
import random 
mes = ["Janeiro", "Fevereiro", "Março", "Abril","Maio","Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"]
estacao = ["Verao", "Inverno", "Outono", "Primavera"]
for i in range(12):
    if i < 3:
        n = 0
    elif 3<= i <6:
        n=1
    elif 6<= i <9:
        n=2
    else:
        n=3
    arq=open("arq "+str(mes[i])+" "+str(estacao[n])+".txt", "w")
    arq.write( random.randint(5,20)*("A minha estacao predileta e "+str(estacao[n])+"especialmente em"+str(mes[i])+"\n"))
    arq.close
    !zip file.zip arq*.txt
    
    

updating: arq Janeiro Verao.txt (stored 0%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
  adding: arq Fevereiro Verao.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
  adding: arq Março Verao.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
  adding: arq Abril Inverno.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
updating: arq Abril Inverno.txt (deflated 93%)
  adding: arq Maio Inverno.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
updating: arq Abril Inverno.txt (deflated 93%)
updating: arq Maio Inverno.txt (deflated 86%)
  adding: arq Junho Inverno.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
updating: arq Abril Inverno.txt (deflated 93%)
updating: arq Maio Inverno.txt (deflated 86%)
updating: arq Junho Inverno.txt (deflated 94%)
  adding: arq Julho Outono.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
updating: arq Abril Inverno.txt (deflated 93%)
updating: arq Maio Inverno.txt (deflated 86%)
updating: arq Junho Inverno.txt (deflated 94%)
updating: arq Julho Outono.txt (deflated 89%)
  adding: arq Agosto Outono.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
updating: arq Abril Inverno.txt (deflated 93%)
updating: arq Maio Inverno.txt (deflated 86%)
updating: arq Junho Inverno.txt (deflated 94%)
updating: arq Julho Outono.txt (deflated 89%)
updating: arq Agosto Outono.txt (deflated 79%)
  adding: arq Setembro Outono.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
updating: arq Abril Inverno.txt (deflated 93%)
updating: arq Maio Inverno.txt (deflated 86%)
updating: arq Junho Inverno.txt (deflated 94%)
updating: arq Julho Outono.txt (deflated 89%)
updating: arq Agosto Outono.txt (deflated 79%)
updating: arq Setembro Outono.txt (deflated 93%)
  adding: arq Outubro Primavera.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
updating: arq Abril Inverno.txt (deflated 93%)
updating: arq Maio Inverno.txt (deflated 86%)
updating: arq Junho Inverno.txt (deflated 94%)
updating: arq Julho Outono.txt (deflated 89%)
updating: arq Agosto Outono.txt (deflated 79%)
updating: arq Setembro Outono.txt (deflated 93%)
updating: arq Outubro Primavera.txt (deflated 92%)
  adding: arq Novembro Primavera.txt (stored 0%)


updating: arq Janeiro Verao.txt (deflated 92%)
updating: arq Fevereiro Inverno.txt (deflated 94%)
updating: arq Março Outono.txt (deflated 88%)
updating: arq Abril Primavera.txt (deflated 91%)
updating: arq Fevereiro Verao.txt (deflated 91%)
updating: arq Março Verao.txt (deflated 93%)
updating: arq Abril Inverno.txt (deflated 93%)
updating: arq Maio Inverno.txt (deflated 86%)
updating: arq Junho Inverno.txt (deflated 94%)
updating: arq Julho Outono.txt (deflated 89%)
updating: arq Agosto Outono.txt (deflated 79%)
updating: arq Setembro Outono.txt (deflated 93%)
updating: arq Outubro Primavera.txt (deflated 92%)
updating: arq Novembro Primavera.txt (deflated 91%)
  adding: arq Dezembro Primavera.txt (stored 0%)
