In [42]:
import numpy as np # Primeiro exercicío
a = np.array([1, 2, 0, 0, 4, 0])
nonzeroind= np.nonzero(a)
print (nonzeroind)

(array([0, 1, 4]),)


In [83]:
import numpy as np# Segundo Exercicío
matriz=np.random.rand(3,2)*10
print (matriz)

[[ 1.85920587  7.65449339]
 [ 0.04058171  0.48116617]
 [ 1.60602423  2.37710952]]


In [84]:
matriz.astype(int)//1


array([[1, 7],
       [0, 0],
       [1, 2]])

In [110]:
import numpy as np# Terceiro Exercicío
matriz=np.random.rand(10,2)*10//1
print (matriz)
print(matriz[0,0])

[[ 8.  7.]
 [ 7.  8.]
 [ 2.  1.]
 [ 5.  6.]
 [ 8.  6.]
 [ 8.  9.]
 [ 4.  9.]
 [ 5.  1.]
 [ 8.  0.]
 [ 0.  9.]]
8.0


In [113]:
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
import numpy as np# Terceiro Exercicío
matriz=np.random.rand(10,2)*10//1
print(cart2pol(matriz[0,0,0]))


IndexError: too many indices for array

In [117]:
matriz[(0,1),(0,0)]

array([ 5.,  1.])