In [1]:
#Exercicio1
import numpy as np
matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)

0
1
4


In [4]:
#exercicio2
import numpy as np
matrix=np.random.rand(3,4)
intmatrix=[]
for i in range(len(matrix)):
    aux=matrix[i]//1
    intmatrix.append(aux)
print(matrix)
print(intmatrix)

[[ 0.71247522  0.82259604  0.07163117  0.60337048]
 [ 0.2061257   0.17375271  0.4021769   0.10081615]
 [ 0.47176382  0.58913561  0.30972212  0.96214402]]
[array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.])]


In [3]:
#exercicio3
import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)        
print(matrix2pol)

[[ 0.24052635  0.76281623]
 [ 0.18357959  0.04859068]
 [ 0.46293421  0.20797885]
 [ 0.57987676  0.24555891]
 [ 0.37443854  0.52311934]
 [ 0.47199139  0.27377255]
 [ 0.79470923  0.19460004]
 [ 0.57442515  0.58218837]
 [ 0.98813271  0.91288954]
 [ 0.60052538  0.17372037]]
[(0.79983844212213195, 1.2653502130464986), (0.18990134640690812, 0.25875091925974114), (0.50750692809858911, 0.4222402176136863), (0.62972710639940277, 0.40057181228605893), (0.64331801205112538, 0.94955785254171121), (0.54564391696032832, 0.52561160728745115), (0.81818820413137527, 0.24014414413831756), (0.81786768518702069, 0.79211009512591091), (1.345278249546636, 0.74583844159264279), (0.62514757921888597, 0.28159375327437181)]


In [8]:
#exercicio 4

import numpy as np

matrix=np.random.rand(100,2)
matrixD=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixD.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print matrixD

[0.20598082492732106, 0.51294469222202876, 0.21552274322080439, 0.62128824290700946, 0.60007696460115156, 0.51055938860033012, 0.55754745940903072, 0.50508626503133858, 0.39656207126388582, 0.19851615635690659, 0.21940137104208735, 0.75081887602141784, 0.62678903398954311, 0.30045871260666934, 0.48386196608493071, 0.017329815876189703, 0.77023143175863473, 0.21360044529383962, 0.2190900625118507, 0.46498895813928137, 0.4438525043577225, 0.16440102623027156, 0.22258744145595982, 0.16076261099109906, 0.38336624980588951, 0.43435114205774134, 0.26594590474652363, 0.42983787197888712, 0.68865501462870027, 0.6859933904624359, 0.4755403322776422, 0.69578620624709675, 0.091923730103536022, 0.2256122417810584, 0.1197939134510005, 0.75482914025639125, 0.32027859015147664, 0.45193494828425423, 0.31026553174525473, 0.34220454245745996, 0.41636108034503905, 0.47733848151948483, 0.54835236146524113, 0.6312074853676054, 0.090480306923867146, 0.21523522053721947, 0.33055161573696556, 0.34548364890536

In [7]:
#EXERCICIO 5
vetor=[0,1,2,3,4,5]
vetor2=[]
for i in range(len(vetor)):
    vetor2.append(vetor[i])
    for i in range(0,3):
        vetor2.append(0)
print(vetor2)

[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
