**1. Encontre índices de elementos não nulos de [1,2,0,0,4,0]**

In [5]:
import numpy as np

In [6]:
   print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


**2. Extrair a parte inteira de uma matriz aleatória**

In [14]:
Z = np.random.uniform(0,10,10)
Z

array([ 8.44303513,  5.12459962,  2.01062199,  3.44548624,  3.47675991,
        6.33233793,  3.41756218,  9.16345642,  2.00094682,  7.61086977])

In [12]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 1.  6.  5.  5.  6.  3.  2.  8.  4.  4.]
[ 1.  6.  5.  5.  6.  3.  2.  8.  4.  4.]
[ 1.  6.  5.  5.  6.  3.  2.  8.  4.  4.]
[1 6 5 5 6 3 2 8 4 4]
[ 1.  6.  5.  5.  6.  3.  2.  8.  4.  4.]


**3.Considere uma matriz aleatória de 10 × 2 que represente coordenadas cartesianas, converta-as em coordenadas polares**

In [7]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 0.70572269  0.84270851  0.51815126  0.38575276  1.14546251  0.86407435
  0.85821975  1.16828477  0.81457837  0.75459189]
[ 0.72263471  0.09028829  0.47966553  1.15336942  0.93013364  1.42822967
  0.36675399  0.80155927  0.62843482  0.93459713]


**4. Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos**

In [8]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.          1.08058978  1.18631344  0.99535669  0.58460278  0.67981756
   0.78263314  0.80568867  0.75837626  0.69775516]
 [ 1.08058978  0.          0.1222127   0.48417632  0.87444756  0.43114837
   0.35683297  0.82005477  0.45032591  0.45175163]
 [ 1.18631344  0.1222127   0.          0.48143017  0.93381425  0.55020701
   0.43197763  0.85091138  0.57235948  0.52882497]
 [ 0.99535669  0.48417632  0.48143017  0.          0.54630036  0.61243651
   0.30595227  0.39549439  0.72678592  0.33568828]
 [ 0.58460278  0.87444756  0.93381425  0.54630036  0.          0.67969959
   0.51984588  0.22894054  0.81907889  0.43102424]
 [ 0.67981756  0.43114837  0.55020701  0.61243651  0.67969959  0.
   0.30728891  0.7458129   0.14118133  0.31642927]
 [ 0.78263314  0.35683297  0.43197763  0.30595227  0.51984588  0.30728891
   0.          0.49996257  0.42887659  0.09686306]
 [ 0.80568867  0.82005477  0.85091138  0.39549439  0.22894054  0.7458129
   0.49996257  0.          0.88593947  0.4398342 ]
 [ 0.7583

**5. Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor**

In [9]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]
