### Exercícios para fazer na aula
#### 1) Encontre índices de elementos não nulos de [1,2,0,0,4,0]
#### 2) Extrair a parte inteira de uma matriz aleatória
#### 3) Considere uma matriz aleatória de 10×2 que represente coordenadas cartesianas, converta-as em coordenadas polares
#### 4) Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos
#### 5) Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?

## 1)

In [1]:
import numpy as np
a= [1,2,0,0,4,0]
matriz = np.array(a)
matriz

array([1, 2, 0, 0, 4, 0])

In [2]:
np.nonzero(a)#indices dos elementos não nulos

(array([0, 1, 4]),)

## 2)

In [3]:
x= np.random.uniform(0,10,5)
x

array([ 7.59014759,  5.99158953,  5.23657108,  8.09499625,  0.84758364])

In [4]:
x.astype(int)

array([7, 5, 5, 8, 0])

## 3)

In [5]:
matriz= np.random.rand(10,2)
matriz

array([[ 0.3754074 ,  0.04869491],
       [ 0.56172846,  0.99865051],
       [ 0.70335348,  0.79560617],
       [ 0.404328  ,  0.10091445],
       [ 0.03180363,  0.31725081],
       [ 0.84264021,  0.77484317],
       [ 0.49633689,  0.21908148],
       [ 0.75724819,  0.74607921],
       [ 0.83590174,  0.40631077],
       [ 0.41658574,  0.04340729]])

In [6]:
C1,C2=matriz[:,0], matriz[:,1]
cartesiana=np.sqrt(C1**2 + C2**2)
print "Cartesiana:",cartesiana
polares= np.arctan2(C2,C1)
print "Polares:",polares

Cartesiana: [ 0.37855239  1.14579304  1.06192998  0.41673116  0.31884094  1.14473773
  0.54253756  1.06304234  0.92941926  0.41884111]
Polares: [ 0.12899195  1.05841633  0.84686511  0.24458862  1.47088253  0.74350755
  0.41567646  0.77796879  0.45244552  0.10382307]


## 4)

In [7]:
A = np.random.rand(100,2)
A

array([[ 0.48519264,  0.12780249],
       [ 0.12173621,  0.55124985],
       [ 0.38600735,  0.16609936],
       [ 0.71123955,  0.78573277],
       [ 0.81095268,  0.14702545],
       [ 0.98260659,  0.93624023],
       [ 0.50437865,  0.30708869],
       [ 0.07999221,  0.71906105],
       [ 0.09551439,  0.1296541 ],
       [ 0.7394574 ,  0.27739663],
       [ 0.66265539,  0.11253611],
       [ 0.91946944,  0.70207743],
       [ 0.54572714,  0.19289517],
       [ 0.30462941,  0.33801051],
       [ 0.64004856,  0.59927313],
       [ 0.96032305,  0.14608028],
       [ 0.26058976,  0.61814893],
       [ 0.79797122,  0.32141417],
       [ 0.42222353,  0.85233919],
       [ 0.7382021 ,  0.93359401],
       [ 0.39024497,  0.93057611],
       [ 0.54388312,  0.68835219],
       [ 0.91856199,  0.38907625],
       [ 0.37740432,  0.06909874],
       [ 0.29892573,  0.20469573],
       [ 0.49135577,  0.71000356],
       [ 0.10635021,  0.4574716 ],
       [ 0.21626384,  0.99150278],
       [ 0.44467891,

In [8]:
coluna1 = [A[:,0]]
coluna1
C = np.array(coluna1)
c1=C.T
coluna2 = [A[:,1]]
coluna2
D = np.array(coluna2)
c2=D.T
distancia= np.sqrt((c1-c1.T)**2 + (c2-c2.T)**2)
distancia

array([[ 0.        ,  0.55803965,  0.10632203, ...,  0.30964405,
         0.66719959,  0.56657653],
       [ 0.55803965,  0.        ,  0.46709756, ...,  0.61837168,
         0.40287947,  0.66422801],
       [ 0.10632203,  0.46709756,  0.        , ...,  0.36617679,
         0.63022637,  0.59545796],
       ..., 
       [ 0.30964405,  0.61837168,  0.36617679, ...,  0.        ,
         0.51858042,  0.27507236],
       [ 0.66719959,  0.40287947,  0.63022637, ...,  0.51858042,
         0.        ,  0.38658006],
       [ 0.56657653,  0.66422801,  0.59545796, ...,  0.27507236,
         0.38658006,  0.        ]])

## 5)

In [46]:
vetor=[1,2,3,4,5]
vetor[1:1]=[0,0,0]
vetor[5:1]=[0,0,0]
vetor[9:1]=[0,0,0]
vetor[13:1]=[0,0,0]
print vetor

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]
