In [1]:
#Encontre índices de elementos não nulos de [1,2,0,0,4,0]

import numpy as np
matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)

0
1
4


In [2]:
#Exercício 2

import numpy as np
matrix=np.random.rand(3,4)
intmatrix=[]
for i in range(len(matrix)):
    aux=matrix[i]//1
    intmatrix.append(aux)
print(matrix)
print(intmatrix)

[[ 0.80572698  0.92785509  0.19705041  0.90324449]
 [ 0.57730066  0.44082826  0.66881056  0.10084942]
 [ 0.21082263  0.47191231  0.49276399  0.0145367 ]]
[array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.])]


In [3]:
#Exercício 3

import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)
print(matrix2pol)

[[ 0.95006534  0.33920269]
 [ 0.35709697  0.37249556]
 [ 0.2000878   0.2098296 ]
 [ 0.13642221  0.46153625]
 [ 0.62438792  0.21561193]
 [ 0.62376335  0.99551133]
 [ 0.02080436  0.80623047]
 [ 0.82157221  0.09698665]
 [ 0.34798008  0.15795944]
 [ 0.38349724  0.9757321 ]]
[(1.0088025626476789, 0.34292465598298327), (0.51601471694464673, 0.8065007579695076), (0.28993721525843802, 0.80915894937229749), (0.48127614406144587, 1.2833968532425901), (0.66056700779079081, 0.33249704170714628), (1.1747865892651161, 1.0110646256646185), (0.80649885050510728, 1.5449975729383127), (0.82727704561149185, 0.11750622991870824), (0.38215353375641936, 0.42611931241487755), (1.0483907966632, 1.1963083100205278)]


In [9]:
#Exercício 4

matrix=np.random.rand(4,2)
matrixD=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixD.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print matrixD

[0.33865599459166063, 0.53804202451117444, 0.47846044507184871, 0.22133417528688198, 0.45384432041960671, 0.42475588856744695, 0.39420762072992427, 0.27478819613500649, 0.94638274929549004, 0.37812153518839609, 0.4969495544196324, 0.72810195818152035, 0.50299432122179699, 0.38667904605354519, 0.37192478076251345, 0.31200527974098946]


In [6]:
#Exercício 5

vetor=[0,1,2,3,4,5]
vetor2=[]
for i in range(len(vetor)):
    vetor2.append(vetor[i])
    for i in range(0,3):
        vetor2.append(0)
print(vetor2)

[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
