In [1]:
import numpy as np
matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)

0
1
4


In [2]:
import numpy as np
matrix=np.random.rand(3,4)
intmatrix=[]
for i in range(len(matrix)):
    aux=matrix[i]//1
    intmatrix.append(aux)
print(matrix)
print(intmatrix)


[[ 0.58121319  0.46950743  0.98663923  0.51782623]
 [ 0.43848495  0.16849944  0.86368539  0.86047547]
 [ 0.36982356  0.78034014  0.50064884  0.34051019]]
[array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.])]


In [3]:
import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)        
print(matrix2pol)

[[ 0.31259702  0.36973726]
 [ 0.07795662  0.8272116 ]
 [ 0.88486332  0.91849088]
 [ 0.04514204  0.57246241]
 [ 0.27428433  0.99922007]
 [ 0.8775145   0.52725594]
 [ 0.16259891  0.72730309]
 [ 0.37193814  0.58581343]
 [ 0.10541461  0.43657649]
 [ 0.21864192  0.46405096]]
[(0.48417201089194117, 0.86894551654373542), (0.83087680272611797, 1.4768336013836343), (1.275385667534664, 0.80404323261417421), (0.5742395130202812, 1.4921032611266756), (1.0361817652237402, 1.3028964881614984), (1.0237336199888762, 0.54104540181051042), (0.7452571312110009, 1.3508489549000595), (0.69391306799063424, 1.0051032476234074), (0.44912278337382039, 1.3338738166444735), (0.51297912856818395, 1.1304863282561963)]


In [4]:
#exercicio4
import numpy as np

matrix=np.random.rand(10,2)
matrixD=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixD.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print matrixD

[0.01087308726742231, 0.43447675457238716, 0.34118635870098074, 0.46143332881527299, 0.51938065208907802, 0.65200358233043354, 0.48779224173131391, 0.31282163930895301, 0.22179610016041471, 0.3014687677314426, 0.38391268839516784, 0.6116993007618019, 0.32448001733453263, 0.12798442543317967, 0.90898922694731665, 1.0416830437375706, 0.82939259737379023, 0.69279720222082442, 0.21058665947917007, 0.11827092022471793, 0.4712681236189239, 0.67630667311150916, 0.38032413552668898, 0.11984247250112877, 0.99613649581551744, 1.1288153494999429, 0.91112056450992895, 0.7791519937098067, 0.29172930316693663, 0.19664536522260387, 0.32370627355098591, 0.57070763957026627, 0.2950363645455753, 0.16327526164131267, 0.84894842941868964, 0.98165050748976879, 0.77377861016031624, 0.63343807647547867, 0.15855879957593172, 0.076577015808756241, 0.59052518361334638, 0.69325838961413488, 0.83712423840610029, 1.035996363461555, 0.095965719389048854, 0.10255023334150411, 0.36878366856839356, 0.31128475737558942

In [6]:
vetor=[0,1,2,3,4,5]
vetor2=[]
for i in range(len(vetor)):
    vetor2.append(vetor[i])
    for i in range(0,3):
        vetor2.append(0)
print(vetor2)
Fim da conversa no bate-papo


SyntaxError: invalid syntax (<ipython-input-6-900830d1dff1>, line 8)