Encontre índices de elementos não nulos de [1,2,0,0,4,0]
Extrair a parte inteira de uma matriz aleatória
Considere uma matriz aleatória de 10×2 que represente coordenadas cartesianas, converta-as em coordenadas polares
Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos
Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?

In [1]:
a = [1,2,0,0,4,0]

for i in range(len(a)):
    if a[i] !=0:
        print (i)

0
1
4


In [12]:
import numpy as np

randmat = np.random.rand(5,10)*10
inteiromat = np.int_(randmat)

print(inteiromat)

[[7 8 7 4 1 5 8 0 8 6]
 [1 3 1 7 4 3 9 4 6 2]
 [5 2 7 5 4 5 7 0 3 2]
 [2 5 0 0 9 8 9 0 9 9]
 [2 3 3 2 7 5 9 2 8 9]]


In [11]:
##Considere uma matriz aleatória de 10×2 que represente coordenadas cartesianas, converta-as em coordenadas polares
import numpy as np

randmat = np.random.rand(10,2)


In [21]:
##Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos
import numpy as np
from numpy import linalg as LA

rvetor = np.int_(np.random.rand(10,2)*10)

vdist = []

for i in range(len(rvetor)):
    for j in range(1,len(rvetor)):
        vdist.append(LA.norm(rvetor[i]-rvetor[j]))

print('Matriz Origem:\n{}\nDistâncias:{}'.format(rvetor, vdist))

Matriz Origem:
[[8 5]
 [8 2]
 [4 8]
 [0 5]
 [2 4]
 [7 1]
 [9 5]
 [1 7]
 [8 0]
 [5 5]]
Distâncias:[3.0, 5.0, 8.0, 6.0827625302982193, 4.1231056256176606, 1.0, 7.2801098892805181, 5.0, 3.0, 0.0, 7.2111025509279782, 8.5440037453175304, 6.324555320336759, 1.4142135623730951, 3.1622776601683795, 8.6023252670426267, 2.0, 4.2426406871192848, 7.2111025509279782, 0.0, 5.0, 4.4721359549995796, 7.6157731058639087, 5.8309518948453007, 3.1622776601683795, 8.9442719099991592, 3.1622776601683795, 8.5440037453175304, 5.0, 0.0, 2.2360679774997898, 8.0622577482985491, 9.0, 2.2360679774997898, 9.4339811320566032, 5.0, 6.324555320336759, 4.4721359549995796, 2.2360679774997898, 0.0, 5.8309518948453007, 7.0710678118654755, 3.1622776601683795, 7.2111025509279782, 3.1622776601683795, 1.4142135623730951, 7.6157731058639087, 8.0622577482985491, 5.8309518948453007, 0.0, 4.4721359549995796, 8.4852813742385695, 1.4142135623730951, 4.4721359549995796, 3.1622776601683795, 5.8309518948453007, 9.0, 7.0710678118654755,

In [20]:
#Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?
v1=[0,1,2,3,4,5]
v2=[]
for i in range(len(v1)):
    v2.append(v1[i])
    for i in range(0,3):
        v2.append(0)
print(v2)

[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
