
## Exercícios para fazer na aula
##### 1)Encontre índices de elementos não nulos de [1,2,0,0,4,0]
##### 2)Extrair a parte inteira de uma matriz aleatória
##### 3)Considere uma matriz aleatória de 10×2 que represente coordenadas cartesianas, converta-as em coordenadas polares
##### 4)Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos
##### 5)Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?


In [9]:
import numpy as np

### 1)

In [10]:
linha=[1,2,0,0,4,0]

In [11]:
linha

[1, 2, 0, 0, 4, 0]

In [12]:
print(np.nonzero(linha))

(array([0, 1, 4]),)


### 2)

In [35]:
matriz=np.random.uniform(0,10,10)

In [36]:
matriz

array([ 9.74020044,  6.98649193,  4.38239938,  3.95731681,  3.64810072,
        8.97207288,  6.29962659,  5.71183339,  4.81215734,  2.53066808])

In [37]:
print(np.floor(matriz))

[ 9.  6.  4.  3.  3.  8.  6.  5.  4.  2.]


### 3)

In [56]:
Z22=np.random.rand(10,2)

In [57]:
Z22

array([[ 0.59157118,  0.51062792],
       [ 0.63098882,  0.07730767],
       [ 0.91293626,  0.84409319],
       [ 0.24268446,  0.51070984],
       [ 0.27031875,  0.90251763],
       [ 0.99462755,  0.74995894],
       [ 0.60812972,  0.05392833],
       [ 0.26438787,  0.28076716],
       [ 0.55267176,  0.71423685],
       [ 0.31338126,  0.52672702]])

In [83]:
A,B=Z22[:,0],Z22[:,1]
R=np.sqrt(A**2+B**2)
G=np.arctan2(B,A)
print('R:',R)
print('G:',G)

R: [ 0.78147126  0.63570698  1.24336074  0.56543814  0.94213073  1.24568149
  0.61051619  0.38565677  0.90309487  0.61290225]
G: [ 0.71209179  0.12191072  0.74623669  1.12719258  1.27978334  0.64606246
  0.08844762  0.81543434  0.91224053  1.03409131]


### 4)

In [60]:
outro=np.random.rand(100,2)
outro

array([[ 0.56635796,  0.23258845],
       [ 0.3624039 ,  0.55523926],
       [ 0.61851126,  0.05176592],
       [ 0.60562947,  0.65462502],
       [ 0.40468063,  0.27132949],
       [ 0.63425611,  0.13543024],
       [ 0.42248604,  0.68093289],
       [ 0.08555898,  0.89441996],
       [ 0.10572769,  0.4074788 ],
       [ 0.15999635,  0.27957102],
       [ 0.84105182,  0.1209368 ],
       [ 0.97690121,  0.78989   ],
       [ 0.09742781,  0.28407448],
       [ 0.68844945,  0.17029906],
       [ 0.53288759,  0.29496681],
       [ 0.63343814,  0.5443915 ],
       [ 0.62165444,  0.2622883 ],
       [ 0.16132259,  0.23333609],
       [ 0.22462998,  0.33451047],
       [ 0.21013815,  0.6362801 ],
       [ 0.93562138,  0.26413453],
       [ 0.19438918,  0.53725899],
       [ 0.79394138,  0.40703967],
       [ 0.48343791,  0.58504924],
       [ 0.02554834,  0.85194513],
       [ 0.37429495,  0.43546095],
       [ 0.23632427,  0.85383214],
       [ 0.61116508,  0.19984393],
       [ 0.1819509 ,

In [61]:
X,Y=np.atleast_2d(outro[:,0]),np.atleast_2d(outro[:,1])
D=np.sqrt( (X-X.T)**2 + (Y-Y.T)**2 )
print(D)

[[ 0.          0.38170775  0.18819339 ...,  0.50823424  0.72758098
   0.74816589]
 [ 0.38170775  0.          0.56486847 ...,  0.29105184  0.40207287
   0.58665406]
 [ 0.18819339  0.56486847  0.         ...,  0.68936156  0.91489251
   0.90944887]
 ..., 
 [ 0.50823424  0.29105184  0.68936156 ...,  0.          0.25452118
   0.29587669]
 [ 0.72758098  0.40207287  0.91489251 ...,  0.25452118  0.          0.36166134]
 [ 0.74816589  0.58665406  0.90944887 ...,  0.29587669  0.36166134  0.        ]]


### 5)

In [62]:
Z=np.array([1,2,3,4,5])
nz=3
Z0=np.zeros(len(Z)+(len(Z)-1)*(nz))
Z0[::nz+1]=Z
print(Z0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


### Exercício 1 - Jogo da Vida (0.25)
1) O Jogo da Vida (The Game of Life) é um autômato celular (cellular automaton) introduzido por John Horton Conway em 1970. Um automato celular consiste de uma rede de células. Cada célula pode estar em um número finito de estados, como morta ou viva. O “jogo” é na verdade uma simulação que permite observar a evolução de um processo a partir de uma certa condição inicial.

2) O jogo se desenvolve sobre uma matriz bi-dimensional que pode ser tão grande quanto se queira. Vamos chamar essa matriz de mapa. Cada posição ou célula do mapa pode estar vazia (= célula morta) ou ocupada por um agente (= célula viva). Cada posição possui também até 8 posições vizinhas: imediatamente acima, abaixo, aos lados e nas diagonais. Em um determinado instante, o mapa contém uma geração de agentes. A geração no instante seguinte é determinada segundo as regras abaixo:

3) Novos agentes nascem em células vazias que possuam exatamente 3 agentes vizinhos;
- **Agentes com 2 ou 3 agentes vizinhos sobrevivem;**
- **Agentes com menos de 2 agentes vizinhos morrem for falta de recursos;**
- **Agentes com mais de 3 agentes vizinhos morrem por excesso de competição.**

In [89]:
jogo=np.random.randint(0,2, size=(8,8))

In [90]:
jogo

array([[0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 1, 0, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 1, 0]])

In [88]:
for i in range(10):
    for j in range(10):

1