#### Exercicio 1

- Gere uma lista com 100 números aleatórios, em seguida o aluno deverá deverá encontrar os intervalos médios dos elementos da lista.

In [38]:
import random 
lista= random.sample(range(0, 100), 100)
lista


[1,
 69,
 24,
 92,
 20,
 25,
 83,
 31,
 62,
 50,
 71,
 65,
 79,
 11,
 96,
 35,
 58,
 33,
 63,
 9,
 86,
 30,
 91,
 39,
 52,
 22,
 6,
 94,
 55,
 34,
 36,
 4,
 43,
 53,
 77,
 78,
 75,
 29,
 54,
 82,
 2,
 48,
 57,
 15,
 90,
 68,
 73,
 19,
 26,
 41,
 89,
 70,
 3,
 13,
 66,
 14,
 28,
 21,
 64,
 0,
 47,
 59,
 12,
 16,
 46,
 56,
 93,
 44,
 87,
 5,
 27,
 97,
 38,
 76,
 37,
 80,
 84,
 23,
 95,
 99,
 18,
 85,
 32,
 51,
 45,
 67,
 74,
 17,
 40,
 72,
 88,
 81,
 10,
 61,
 98,
 8,
 60,
 49,
 7,
 42]

In [0]:
imedio=[]

for i in range(0,99):
    imedio.append((lista[i]+lista[i+1])/2.)

print imedio

#### Exercicio 2
Faça um programa que leia um número indeterminado de valores, correspondentes a notas, encerrando a entrada de dados quando for informado um valor igual a -1 (que não deve ser armazenado). Após esta entrada de dados, faça:
- Mostre a quantidade de valores que foram lidos; (ok)
- Exiba todos os valores na ordem em que foram informados, um ao lado do outro; (ok)
- Exiba todos os valores na ordem inversa à que foram informados, um abaixo do outro; (não feito)
- Calcule e mostre a soma dos valores; (ok)
- Calcule e mostre a média dos valores; (ok)
- Calcule e mostre a quantidade de valores acima da média calculada; (ok)
- Calcule e mostre a quantidade de valores abaixo de sete; (ok)
- Encerre o programa com uma mensagem; (ok)

In [2]:
    nota= input('Insira as notas dos alunos')
n=[]
n.append(nota)
while nota !=(-1):
    nota= input('Insira as notas dos alunos')
    n.append(nota)
    if nota == -1:
        n.remove(nota)
        break;

Insira as notas dos alunos 5.5

Insira as notas dos alunos 9

Insira as notas dos alunos 3.6

Insira as notas dos alunos 8.7

Insira as notas dos alunos 0.5

Insira as notas dos alunos -1

In [3]:
print 'A quantidade de valores lidos foram:', len(n)

A quantidade de valores lidos foram: 5


In [4]:
import numpy as np
print n

[5.5, 9, 3.6, 8.7, 0.5]


In [5]:
print np.ravel(n)

[ 5.5  9.   3.6  8.7  0.5]


In [6]:

strn=" "
for i in n:
    strn = strn+str(i)+" "
strn

' 5.5 9 3.6 8.7 0.5 '

In [8]:
#precisa ser inverso!!
strn=" "
for i in n:
    strn = "\n"+str(i)+strn
print strn


0.5
8.7
3.6
9
5.5 


In [9]:
soma=sum(n)
print 'A soma dos valores de' , n, 'é:', soma

A soma dos valores de [5.5, 9, 3.6, 8.7, 0.5] é: 27.3


In [10]:
media= soma/len(n)
print 'A média dos valores de', n, 'é:', media

A média dos valores de [5.5, 9, 3.6, 8.7, 0.5] é: 5.46


In [11]:
for elem in n:
    if elem> media:
        print elem

5.5
9
8.7


In [12]:
for elem in n:
    if elem<7:
        print elem

5.5
3.6
0.5


In [13]:
print 'O programa termina aqui. Até mais e obrigado pelos peixes!'

O programa termina aqui. Até mais e obrigado pelos peixes!


#### Exercicio 3
- Calcule as raízes da equação do 2◦ grau ($Ax^2 + Bx + C = 0$) sendo os valores de A, B e C fornecidos pelo usuário, levando em consideração a existência de raízes complexas.**

In [89]:
A= float(input("Insira A: "))
B= float(input("Insira B: ") )
C= float(input("Insira C: "))


Insira A:  2

Insira B:  2.

Insira C:  2.0

In [90]:
## from math import sqrt
delta= (B**2)-4*A*C
while delta<0:
    print ("Delta menor que zero, raízes complexas. Por favor, insira outros valores de A, B e C: ")
    A= input("Insira A: ")
    B= input("Insira B: ") 
    C= input("Insira C: ")
    float(A), float(B), float(C)
    delta= (B**2)-4*A*C

x1= (-B+(delta)**(1/2))/(2*A)
x2= (-B-(delta)**(1/2))/(2*A)
print "x1:",x1
print "x2:",x2  

Delta menor que zero, raízes complexas. Por favor, insira outros valores de A, B e C: 


Insira A:  2.

Insira B:  4.8

Insira C:  9

Delta menor que zero, raízes complexas. Por favor, insira outros valores de A, B e C: 


Insira A:  9.

Insira B:  -3

Insira C:  2

Insira A:  

Delta menor que zero, raízes complexas. Por favor, insira outros valores de A, B e C: 


Insira B:  4

Insira C:  5.

Delta menor que zero, raízes complexas. Por favor, insira outros valores de A, B e C: 


Insira A:  7.

Insira B:  4.

Insira C:  -3.

x1: -0.214285714286
x2: -0.357142857143


#### Exercícios 4
- Crie 12 arquivos, chamados de 'arq_mes_estação.txt'. Cada um deles contendo a frase: "A minha estação predileta é 'estação', especialmente 'mês'"  repetida um número aleatório de vezes, entre 5 e 20. Comprima essas arquivos usando o comando gzip. Faça isso utilizando o conceito de dicionários.

In [23]:
from random import randint
with open('estacao12.txt','w') as f:
    print (f.write(randint(5,20)*"A minha estação preferida é Inverno, especialmente fevereiro \n"))

None


In [24]:
!ls 

arq_dezembro_inverno.txt  estacao2.txt	estacao8.txt
arq_janeiero_inverno.txt  estacao3.txt	estacao9.txt
Cronograma.ipynb	  estacao4.txt	estacao.txt
estacao10.txt		  estacao5.txt	Exerciciosrevisao22.05.2017.ipynb
estacao11.txt		  estacao6.txt	notaealu
estacao12.txt		  estacao7.txt	Revisão.ipynb


In [25]:
!gzip estacao2.txt estacao8.txt arq_janeiero_inverno.txt  estacao3.txt estacao9.txt estacao4.txt estacao.txt estacao10.txt		  estacao5.txt
!gzip estacao11.txt  estacao6.txt
!gzip estacao12.txt   estacao7.txt

In [26]:
!ls

arq_dezembro_inverno.txt     estacao2.txt.gz  estacao8.txt.gz
arq_janeiero_inverno.txt.gz  estacao3.txt.gz  estacao9.txt.gz
Cronograma.ipynb	     estacao4.txt.gz  estacao.txt.gz
estacao10.txt.gz	     estacao5.txt.gz  Exerciciosrevisao22.05.2017.ipynb
estacao11.txt.gz	     estacao6.txt.gz  notaealu
estacao12.txt.gz	     estacao7.txt.gz  Revisão.ipynb


#### Exercícios 5
1. Com base nos dados de https://pt.wikipedia.org/wiki/Lista_de_epis%C3%B3dios_de_Pok%C3%A9mon Construa um  dataframe para armazenar 
as informações sobre os episódios de Pokemon, contendo: 
- Série
- Geração
- Temporada
- Primeiro Episódio
- Último Episódio
- Região
2. Descubra qual a geração mais longeva
3. Descubra quantas temporadas durou cada série

In [27]:
import pandas as pd

#DataFrame
data={
'Série': ['Série Original','Série Original','Série Original','Série Original','Série Original','Geração Avançada','Geração Avançada',
        'Geração Avançada','Geração Avançada','Diamante e Pérola','Diamante e Pérola','Diamante e Pérola',
        'Diamante e Pérola','Preto e Branco','Preto e Branco','Preto e Branco','XY','XY','XY','Sun and Moon'],
'Geração': ['Primeira','Primeira','Segunda','Segunda','Segunda','Terceira','Terceira','Terceira','Terceira',
            'Quarta','Quarta','Quarta','Quarta','Quinta','Quinta','Quinta','Sexta','Sexta','Sexta','Sétima'],
'Temporada': ['Liga Indigo', 'As Aventuras nas Ilhas Laranja','A Jornada Johto','Campeões da Liga Johto','Master Quest','Pokémon: Avançado',
      'Desafio Avançado','Batalha Avançada','Batalha da Fronteira','Diamante e Pérola','Batalha Dimensional','Batalhas Galácticas',
     'Vencedores da Liga Sinnoh','Preto e Branco','Destinos Rivais', 'Aventuras em Unova (e Mais Além)','A Série XY','Kalos Quest','XY & Z',
      'Sun and Moon'],
'Primeiro Episódio': [1,84,119,160,212,277,317,369,422, 469,521,573,626,660,708,757,804,853,898,947] ,
'Último Episódio': [83,118,159,211,276,316,368,421,468,520,572,625,659,707,756,803,852,897,946,'Não tem'],

'Região': ['Kanto','Ilhas Laranja','Johto','Johto','Johto','Hoenn','Hoenn','Hoenn','Kanto','Sinnoh','Sinnoh','Sinnoh','Sinnoh','Unova','Unova',
           'Unova','Kalos','Kalos','Kalos','Alola']}

df = pd.DataFrame(data, columns=['Série','Geração','Temporada','Primeiro Episódio','Último Episódio','Região'])
df

Série 
 Geração 
 Temporada 
 Primeiro Episódio 
 Último Episódio 
 Região 
 
 
 
 
 0 
 Série Original 
 Primeira 
 Liga Indigo 
 1 
 83 
 Kanto 
 
 
 1 
 Série Original 
 Primeira 
 As Aventuras nas Ilhas Laranja 
 84 
 118 
 Ilhas Laranja 
 
 
 2 
 Série Original 
 Segunda 
 A Jornada Johto 
 119 
 159 
 Johto 
 
 
 3 
 Série Original 
 Segunda 
 Campeões da Liga Johto 
 160 
 211 
 Johto 
 
 
 4 
 Série Original 
 Segunda 
 Master Quest 
 212 
 276 
 Johto 
 
 
 5 
 Geração Avançada 
 Terceira 
 Pokémon: Avançado 
 277 
 316 
 Hoenn 
 
 
 6 
 Geração Avançada 
 Terceira 
 Desafio Avançado 
 317 
 368 
 Hoenn 
 
 
 7 
 Geração Avançada 
 Terceira 
 Batalha Avançada 
 369 
 421 
 Hoenn 
 
 
 8 
 Geração Avançada 
 Terceira 
 Batalha da Fronteira 
 422 
 468 
 Kanto 
 
 
 9 
 Diamante e Pérola 
 Quarta 
 Diamante e Pérola 
 469 
 520 
 Sinnoh 
 
 
 10 
 Diamante e Pérola 
 Quarta 
 Batalha Dimensional 
 521 
 572 
 Sinnoh 
 
 
 11 
 Diamante e Pérola 
 Quarta 
 Batalhas Galácticas 
 573 
 625 
 Sinnoh 
 
 
 12 
 Diamante e Pérola 
 Quarta 
 Vencedores da Liga Sinnoh 
 626 
 659 
 Sinnoh 
 
 
 13 
 Preto e Branco 
 Quinta 
 Preto e Branco 
 660 
 707 
 Unova 
 
 
 14 
 Preto e Branco 
 Quinta 
 Destinos Rivais 
 708 
 756 
 Unova 
 
 
 15 
 Preto e Branco 
 Quinta 
 Aventuras em Unova (e Mais Além) 
 757 
 803 
 Unova 
 
 
 16 
 XY 
 Sexta 
 A Série XY 
 804 
 852 
 Kalos 
 
 
 17 
 XY 
 Sexta 
 Kalos Quest 
 853 
 897 
 Kalos 
 
 
 18 
 XY 
 Sexta 
 XY & Z 
 898 
 946 
 Kalos 
 
 
 19 
 Sun and Moon 
 Sétima 
 Sun and Moon 
 947 
 Não tem 
 Alola

In [28]:
prim=0
seg=0
ter=0
qua=0
qui=0
sex=0

for i in range(19):
    if df.ix[i]['Geração']== 'Primeira':
        prim= prim+df['Último Episódio'][i]-df['Primeiro Episódio'][i]+1
    if df.ix[i]['Geração']== 'Segunda':
        seg= seg+df['Último Episódio'][i]-df['Primeiro Episódio'][i]+1
    if df.ix[i]['Geração']== 'Terceira':
        ter= ter+df['Último Episódio'][i]-df['Primeiro Episódio'][i]+1
    if df.ix[i]['Geração']== 'Quarta':
         qua= qua+df['Último Episódio'][i]-df['Primeiro Episódio'][i]+1
    if df.ix[i]['Geração']== 'Quinta':
         qui= qui+df['Último Episódio'][i]-df['Primeiro Episódio'][i]+1
    if df.ix[i]['Geração']== 'Sexta':
         sex= sex+df['Último Episódio'][i]-df['Primeiro Episódio'][i]+1
epis=[prim,seg,ter,qua,qui,sex]
temps={'Primeira':prim,'Segunda':seg,'Terceira':ter,'Quarta':qua,'Quinta':qui,'Sexta':sex}
gerlongeva= max(temps)

for elem in epis:
    #print elem
    if elem==max(epis):
        print 'A geração mais longeva é a', gerlongeva, 'com', elem, 'episódios' 

A geração mais longeva é a Terceira com 192 episódios


In [29]:
print 'A Série Original durou', len([elem for elem in df['Série'] if elem == 'Série Original']) , 'temporadas'
print 'A Geração Avançada durou', len([elem for elem in df['Série'] if elem == 'Geração Avançada']), 'temporadas'
print 'Diamante e Pérola durou', len([elem for elem in df['Série'] if elem == 'Diamante e Pérola']), 'temporadas'
print 'Preto e Branco durou', len([elem for elem in df['Série'] if elem == 'Preto e Branco']), 'temporadas'
print 'XY durou', len([elem for elem in df['Série'] if elem == 'XY']), 'temporadas'
print 'Sun and Moon durou', len([elem for elem in df['Série'] if elem == 'Sun and Moon']), 'temporada'

A Série Original durou 5 temporadas
A Geração Avançada durou 4 temporadas
Diamante e Pérola durou 4 temporadas
Preto e Branco durou 3 temporadas
XY durou 3 temporadas
Sun and Moon durou 1 temporada


#### Exercício 6
- Passo 1: Gere um arquivo com 10 notas de cinco alunos (Deve conter o nome do aluno e as notas). (ok)
- Passo 2: Em seguida crie uma array em numpy com essas notas. (ok)
- Passo 3: Crie um DataFrame dessas notas. (ok)
- Passo 4: Identifique qual menor nota e quem foi o aluno que obteve essa nota (ok)
- Passo 5: Identifique o aluno que tirou as melhores notas. (ok)

In [282]:
aluno=[]
nota=[]
for i in range(5):
    aluno.append(raw_input ('insira o nome do aluno'))
for i in aluno:
    nota.append(input ('Insira as notas aqui'))
    nota.append(input ('Insira as notas aqui'))


insira o nome do aluno Vanessa

insira o nome do aluno Felipe

insira o nome do aluno Elian

insira o nome do aluno Ana

insira o nome do aluno Joao

Insira as notas aqui 10

Insira as notas aqui 9

Insira as notas aqui 8

Insira as notas aqui 7

Insira as notas aqui 3.4

Insira as notas aqui 4.2

Insira as notas aqui 5.7

Insira as notas aqui 6.1

Insira as notas aqui 5.5

Insira as notas aqui 4.9

In [283]:
print nota
print aluno


[10, 9, 8, 7, 3.4, 4.2, 5.7, 6.1, 5.5, 4.9]
['Vanessa', 'Felipe', 'Elian', 'Ana', 'Joao']


In [284]:
import pandas as pd
notaal=range(9)
for i in range(9):
    notaal[i]=[nota[i],nota[i+1]]

del notaal[1::2]

notaealu=zip(aluno,notaal)
print 'Os alunos e suas respectivas notas são:\n', notaealu
notss=str(notaealu)

with open('notaealu','w')as arq:
    arq.write(notss)

Os alunos e suas respectivas notas são:
[('Vanessa', [10, 9]), ('Felipe', [8, 7]), ('Elian', [3.4, 4.2]), ('Ana', [5.7, 6.1]), ('Joao', [5.5, 4.9])]


In [285]:
import numpy as np
nots=np.array(nota)
print nots


[ 10.    9.    8.    7.    3.4   4.2   5.7   6.1   5.5   4.9]


In [405]:
import pandas as pd 
df=pd.DataFrame(nots)
dff=pd.DataFrame(notaealu)#,index=['Nota e Aluno', 'Nota e Aluno', 'Nota e Aluno', 'Nota e Aluno','Nota e Aluno'])
dff['Aluno']=dff[0]
dff['Notas']=dff[1]
dff=dff.drop(0,axis=1)
dff=dff.drop(1,axis=1)
print dff
dff['Maior nota']=[max(elem) for elem in notaal]
dff['Menor nota']=[min(elem) for elem in notaal]
dff=dff.drop('Notas', axis=1)
dff

     Aluno       Notas
0  Vanessa     [10, 9]
1   Felipe      [8, 7]
2    Elian  [3.4, 4.2]
3      Ana  [5.7, 6.1]
4     Joao  [5.5, 4.9]


Aluno 
 Maior nota 
 Menor nota 
 
 
 
 
 0 
 Vanessa 
 10.0 
 9.0 
 
 
 1 
 Felipe 
 8.0 
 7.0 
 
 
 2 
 Elian 
 4.2 
 3.4 
 
 
 3 
 Ana 
 6.1 
 5.7 
 
 
 4 
 Joao 
 5.5 
 4.9

In [479]:
for elem in dff['Menor nota']:
    for i in range(len(dff['Menor nota'])):
        if elem == dff['Menor nota'].min():
            if dff.loc[i]['Menor nota']== dff['Menor nota'].min():
                print 'O aluno com menor nota é:', dff.loc[i]['Aluno'], 'e a nota é', dff.loc[i]['Menor nota']
           

O aluno com menor nota é: Elian e a nota é 3.4


In [482]:
for elem in dff['Maior nota']:
    for i in range(len(dff['Maior nota'])):
        if elem == dff['Maior nota'].max():
            if dff.loc[i]['Maior nota']== dff['Maior nota'].max():
                print 'O aluno com maior nota é:', dff.loc[i]['Aluno'], 'e a nota é', dff.loc[i]['Maior nota']
           

O aluno com maior nota é: Vanessa e a nota é 10.0


#### Exercicio 7
- O Jogo da Vida (The Game of Life) é um autômato celular (cellular automaton) introduzido por John Horton Conway em 1970. Um automato celular consiste de uma rede de células. Cada célula pode estar em um número finito de estados, como morta ou viva. O “jogo” é na verdade uma simulação que permite observar a evolução de um processo a partir de uma certa condição inicial.
- O jogo se desenvolve sobre uma matriz bi-dimensional que pode ser tão grande quanto se queira. Vamos chamar essa matriz de mapa. Cada posição ou célula do mapa pode estar vazia (= célula morta) ou ocupada por um agente (= célula viva). Cada posição possui também até 8 posições vizinhas: imediatamente acima, abaixo, aos lados e nas diagonais. Em um determinado instante, o mapa contém uma geração de agentes. A geração no instante seguinte é determinada segundo as regras abaixo:
- Novos agentes nascem em células vazias que possuam exatamente 3 agentes vizinhos;
- **Agentes com 2 ou 3 agentes vizinhos sobrevivem;**
- **Agentes com menos de 2 agentes vizinhos morrem for falta de recursos;**
- **Agentes com mais de 3 agentes vizinhos morrem por excesso de competição.**

In [52]:
import numpy as np

def iterate_1(Z):
    # Contagem vizinhança
    N = np.zeros(Z.shape, int)
    N[1:-1,1:-1] += (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
                     Z[1:-1,0:-2]                + Z[1:-1,2:] +
                     Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    N_ = N.ravel()
    Z_ = Z.ravel()

    # Aplicação das regras
    R1 = np.argwhere( (Z_==1) & (N_ < 2) )
    R2 = np.argwhere( (Z_==1) & (N_ > 3) )
    R3 = np.argwhere( (Z_==1) & ((N_==2) | (N_==3)) )
    R4 = np.argwhere( (Z_==0) & (N_==3) )

    # Definir novos valores
    Z_[R1] = 0
    Z_[R2] = 0
    Z_[R3] = Z_[R3]
    Z_[R4] = 1

    # Garantia de que as fronteiras permaneçam nulas
    Z[0,:] = Z[-1,:] = Z[:,0] = Z[:,-1] = 0


def iterate_2(Z):
    # Contagem vizinhança
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Aplicação das regras
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z


Z = np.array([[0,0,0,0,0,0],
              [0,0,0,1,0,0],
              [0,1,0,1,0,0],
              [0,0,1,1,0,0],
              [0,0,0,0,0,0],
              [0,0,0,0,0,0]])

print Z
print
for i in range(4): iterate_2(Z)
print Z


[[0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 1 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 1 0]
 [0 0 0 1 1 0]
 [0 0 0 0 0 0]]


In [53]:

#para muitos pontos, visualização gráfica


In [54]:
for i in range(100): iterate_1(Z)

In [55]:
import matplotlib.pyplot as plt

size = np.array(Z.shape)
dpi = 72.0
figsize= size[1]/float(dpi),size[0]/float(dpi)
fig= plt.figure(figsize=figsize, dpi=dpi, facecolor="white")
fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon=False)
plt.imshow(U,interpolation='nearest', cmap=plt.cm.Purples)
plt.xticks([]), plt.yticks([])
plt.show()

NameError: name 'U' is not defined

In [56]:
size = np.array(Z.shape)
dpi = 72.0
figsize= size[1]/float(dpi),size[0]/float(dpi)
fig=plt.figure(figsize=figsize, dpi=dpi,facecolor="white")
fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon=False)
plt.imshow(Z,interpolation='nearest', cmap=plt.cm.gray_r)
plt.xticks([]), plt.yticks([])
plt.show()

#### Exercicio 8
Considere um conjunto de 10 triplets descrevendo 10 triângulos (com vértices compartilhados), encontrar o conjunto de segmentos de linha única compondo todos os triângulos 