## Exercício 01.1 - Encontre índices de elementos não nulos de [1,2,0,0,4,0]



In [10]:
import numpy as np

a= [1,2,0,0,4,0]
matriz = np.array(a)

for i in range(len(matriz)):
    if matriz[i] != 0:
        print('Número: {} Índice: \t{}'.format(matriz[i], i))
        
        
        

Número: 1 Índice: 	0
Número: 2 Índice: 	1
Número: 4 Índice: 	4


## Exercício 01.2 - Extrair a parte inteira de uma matriz aleatória


In [23]:
import numpy as np

rmatriz = np.random.rand(3,4)*10
imatriz = np.int_(rmatriz)
print('Matriz aleatória:\n{}\n\n Matriz inteira:\n{}'.format(rmatriz, imatriz))



Matriz aleatória:
[[ 6.41519757  4.02826433  4.99168663  3.15267294]
 [ 4.45452663  8.49032824  8.19212893  3.45841599]
 [ 7.70926957  3.64995969  0.7047639   4.78078647]]

 Matriz inteira:
[[6 4 4 3]
 [4 8 8 3]
 [7 3 0 4]]


## Exercício 01.3 - Considere uma matriz aleatória de 10×2 que represente coordenadas cartesianas, converta-as em coordenadas polares

In [44]:
import numpy as np
from numpy import linalg as LA
import math as m

rmatriz = np.int_(np.random.rand(10,2)*10)

x = list(rmatriz[:,0])
y = list(rmatriz[:,1])

for i in range(len(x)):
    ro = m.sqrt(m.pow(x[i],2)+m.pow(y[i],2))
    teta = m.atan2(y[i],x[i])
    rx = ro*m.cos(teta)
    ry = ro*m.sin(teta)
    print(rx, ry)


(2.0, 5.0)
(3.999999999999999, 6.999999999999999)
(9.0, 3.9999999999999996)
(9.0, 3.0)
(3.0, 0.0)
(1.0000000000000002, 2.0)
(7.0, 0.0)
(9.0, 8.999999999999998)
(9.0, 3.9999999999999996)
(6.0, 3.999999999999999)


## Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos


In [55]:
import numpy as np
from numpy import linalg as LA

rvetor = np.int_(np.random.rand(10,2)*10)

vdist = []

for i in range(len(rvetor)):
    for j in range(1,len(rvetor)):
        vdist.append(LA.norm(rvetor[i]-rvetor[j]))

print('Matriz Origem:\n{}\nDistâncias:{}'.format(rvetor, vdist))

Matriz Origem:
[[4 1]
 [9 6]
 [5 3]
 [9 6]
 [4 8]
 [3 6]
 [9 6]
 [8 1]
 [7 0]
 [4 8]]
Distâncias:[7.0710678118654755, 2.2360679774997898, 7.0710678118654755, 7.0, 5.0990195135927845, 7.0710678118654755, 4.0, 3.1622776601683795, 7.0, 0.0, 5.0, 0.0, 5.3851648071345037, 6.0, 0.0, 5.0990195135927845, 6.324555320336759, 5.3851648071345037, 5.0, 0.0, 5.0, 5.0990195135927845, 3.6055512754639891, 5.0, 3.6055512754639891, 3.6055512754639891, 5.0990195135927845, 0.0, 5.0, 0.0, 5.3851648071345037, 6.0, 0.0, 5.0990195135927845, 6.324555320336759, 5.3851648071345037, 5.3851648071345037, 5.0990195135927845, 5.3851648071345037, 0.0, 2.2360679774997898, 5.3851648071345037, 8.0622577482985491, 8.5440037453175304, 0.0, 6.0, 3.6055512754639891, 6.0, 2.2360679774997898, 0.0, 6.0, 7.0710678118654755, 7.2111025509279782, 2.2360679774997898, 0.0, 5.0, 0.0, 5.3851648071345037, 6.0, 0.0, 5.0990195135927845, 6.324555320336759, 5.3851648071345037, 5.0990195135927845, 3.6055512754639891, 5.0990195135927845, 8.062

## Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?


In [56]:
import numpy as np

vin = [1,2,3,4,5]
vout=[]
for i in range(len(vin)):
    vout.append(vin[i])
    for i in range(0,3):
        vout.append(0)
print(vout)


[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
