# Ex: 1 
#### Gere uma lista com 100 números aleatórios, em seguida o aluno deverá deverá encontrar os intervalos médios dos elementos da lista.

In [6]:
import random
lista = random.sample(range(0, 100), 100)
i=1
into=[]
while i< len(lista):
    into.append ((lista[i-1]-lista[i]))
    i = i+1
    
print ('lista', lista)
print ('intervalos', into)

('lista', [87, 77, 0, 50, 88, 93, 69, 14, 49, 94, 8, 39, 45, 86, 91, 35, 62, 78, 83, 10, 5, 12, 6, 56, 68, 55, 34, 57, 31, 82, 21, 46, 75, 1, 67, 53, 18, 59, 20, 26, 41, 13, 29, 48, 90, 11, 95, 76, 27, 25, 81, 98, 40, 89, 74, 92, 33, 51, 17, 54, 38, 73, 24, 9, 23, 19, 7, 58, 99, 2, 84, 61, 97, 85, 71, 96, 37, 63, 47, 79, 43, 72, 15, 70, 4, 80, 52, 22, 44, 65, 66, 16, 60, 32, 42, 36, 64, 3, 30, 28])
('intervalos', [10, 77, -50, -38, -5, 24, 55, -35, -45, 86, -31, -6, -41, -5, 56, -27, -16, -5, 73, 5, -7, 6, -50, -12, 13, 21, -23, 26, -51, 61, -25, -29, 74, -66, 14, 35, -41, 39, -6, -15, 28, -16, -19, -42, 79, -84, 19, 49, 2, -56, -17, 58, -49, 15, -18, 59, -18, 34, -37, 16, -35, 49, 15, -14, 4, 12, -51, -41, 97, -82, 23, -36, 12, 14, -25, 59, -26, 16, -32, 36, -29, 57, -55, 66, -76, 28, 30, -22, -21, -1, 50, -44, 28, -10, 6, -28, 61, -27, 2])


# ex.2

##### Faça um programa que leia um número indeterminado de valores, correspondentes a notas, encerrando a entrada de dados quando for informado um valor igual a -1 (que não deve ser armazenado). Após esta entrada de dados, faça:
##### Mostre a quantidade de valores que foram lidos;
 ##### Exiba todos os valores na ordem em que foram informados, um ao lado do outro;
##### Exiba todos os valores na ordem inversa à que foram informados, um abaixo do outro;
##### Calcule e mostre a soma dos valores;
##### Calcule e mostre a média dos valores;
##### Calcule e mostre a quantidade de valores acima da média calculada;
##### Calcule e mostre a quantidade de valores abaixo de sete;
##### Encerre o programa com uma mensagem;

In [7]:
i=0
nota = []
while i !=-1:
    y=input('digite nota')
    if y == -1:
        print "notas", nota
        i=-1
    else:
        nota.append(y)
        i=i+1
        
print "qtd de valores", len(nota)
print "soma dos valores", sum(nota)
y=sum(nota)/len(nota)
print "media", y 



digite nota 2

digite nota 3

digite nota -1

notas [2, 3]
qtd de valores 2
soma dos valores 5
media 2


#### Exercicio 3
Calcule as raízes da equação do 2◦ grau ( Ax2+Bx+C=0Ax2+Bx+C=0 ) sendo os valores de A, B e C fornecidos pelo usuário, levando em consideração a existência de raízes complexas.**

In [7]:
a = input("A= ")
b = input("B= ")
c = input("C= ")

import math
 
delta = (b*b-4*a*c)
print 'Delta=', delta

if delta < 0:
    print "Possui soluçao complexa"
elif delta == 0:
    raiz = ((-1*b+math.sqrt(delta))/(2*a))
    print "A raiz da equação é: ",raiz
else:
    raiz1 = ((-1*b + math.sqrt(delta))/(2*a))
    raiz2 = ((-1*b - math.sqrt(delta))/(2*a))   
    print " raiz x1 = ",raiz1,"  raiz x2 = ",raiz2


A=  3

B=  4

C=  5

Delta= -44
Possui soluçao complexa


### Exercício 6
Passo 1: Gere um arquivo com 10 notas de cinco alunos (Deve conter o nome do aluno e as notas).
Passo 2: Em seguida crie uma array em numpy com essas notas.
Passo 3: Crie um DataFrame dessas notas.
Passo 4: Identifique qual menor nota e quem foi o aluno que obteve essa nota
Passo 5: Identifique o aluno que tirou as melhores notas.


In [30]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
i=0
nota = []
while i !=10:
    y=input('digite nota do aluno')
    nota.append(y)
    a= np.array(nota)  
    i=i+1

print 'notas dos alunos= ', a
x= DataFrame(a, index =['ALUNO 1', 'AL 2','AL 3','AL 4','AL 5', 'AL 6', 'AL 7', 'AL 8', 'AL 9', 'AL 10'])
print 'tabela de notas',x


digite nota do aluno 1

digite nota do aluno 2

digite nota do aluno 3

digite nota do aluno 4

digite nota do aluno 5

digite nota do aluno 6

digite nota do aluno 7

digite nota do aluno 8

digite nota do aluno 9

digite nota do aluno 0

notas dos alunos=  [1 2 3 4 5 6 7 8 9 0]
tabela de notas          0
ALUNO 1  1
AL 2     2
AL 3     3
AL 4     4
AL 5     5
AL 6     6
AL 7     7
AL 8     8
AL 9     9
AL 10    0


###### Exercícios 4
Crie 12 arquivos, chamados de 'arq_mes_estação.txt'. Cada um deles contendo a frase: "A minha estação predileta é 'estação', especialmente 'mês'" repetida um número aleatório de vezes, entre 5 e 20. Comprima essas arquivos usando o comando gzip. Faça isso utilizando o conceito de dicionários.

#### exercicio 4 foi resolvido da aula 24/04

### Exercícios 5
Com base nos dados de https://pt.wikipedia.org/wiki/Lista_de_epis%C3%B3dios_de_Pok%C3%A9mon Construa um dataframe para armazenar as informações sobre os episódios de Pokemon, contendo:
Série
Geração
Temporada
Primeiro Episódio
Último Episódio
Região
Descubra qual a geração mais longeva
Descubra quantas temporadas durou cada série

In [1]:
import pandas as pd
import numpy as np

In [2]:
def preenche(lis):
    for elem in range(1,len(lis)):
        if lis[elem]!=lis[elem]: #truque sujo!
            lis[elem]=lis[elem-1]
    return lis

def sint(x):
    try: 
        return int(x)
    except:
        return 947+20+1
    


In [3]:
lispoktab=pd.read_html(" pokemon.html")
df=lispoktab[0]
df.ix[2]=np.roll(df.ix[2],2)
df.ix[3]=np.roll(df.ix[3],1)
df.ix[4]=np.roll(df.ix[4],2)
df.ix[5]=np.roll(df.ix[5],2)
df.ix[7]=np.roll(df.ix[7],2)
df.ix[8]=np.roll(df.ix[8],2)
df.ix[9]=np.roll(df.ix[9],2)
df.ix[11]=np.roll(df.ix[11],2)
df.ix[12]=np.roll(df.ix[12],2)
df.ix[13]=np.roll(df.ix[13],2)
df.ix[15]=np.roll(df.ix[15],2)
df.ix[16]=np.roll(df.ix[16],2)
df.ix[18]=np.roll(df.ix[18],2)
df.ix[19]=np.roll(df.ix[19],2)


df.columns=df.ix[0] # muda o nome das colunas
df=df.drop(0) # elimina a primeira linha
df['Série']=preenche(list(df['Série'])) # elimina elementos com Nan
df['Geração']=preenche(list(df['Geração']))
df['Região']=preenche(list(df['Região']))
df['Episódios']=[episodio[0:-7] for episodio in df['Episódios']] # elimina parte final 
df['Primeiro']=[int(episodio[0:3]) for episodio in df['Episódios']] # separa em duas partes
df['Último']=[sint(episodio[4:-1]) for episodio in df['Episódios']]

/projects/sage/sage-7.5/local/lib/python2.7/site-packages/pandas/indexes/base.py:1396: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return key in self._engine
/projects/sage/sage-7.5/local/lib/python2.7/site-packages/pandas/indexes/base.py:2134: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return self._engine.get_loc(key)
/projects/sage/sage-7.5/local/lib/python2.7/site-packages/pandas/indexes/base.py:2136: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return self._engine.get_loc(self._maybe_cast_indexer(key))


KeyError: 'S\xc3\xa9rie'

In [4]:
df

Série 
 Geração 
 Temporada 
 Descrição 
 Episódios 
 Região 
 
 
 
 
 1 
 Série Original 
 Primeira 
 Liga Índigo 
 Mostra a jornada de Ash, Misty e Brock na Liga... 
 001-083 (lista) 
 Kanto 
 
 
 2 
 NaN 
 NaN 
 Aventuras nas Ilhas Laranja 
 Mostra a jornada de Ash, Misty e Tracey na Lig... 
 084-118 (lista) 
 Ilhas Laranja 
 
 
 3 
 NaN 
 Segunda 
 A Jornada Johto 
 Inicia a jornada de Ash, Misty e Brock em Joht... 
 119-159 (lista) 
 Johto 
 
 
 4 
 NaN 
 NaN 
 Campeões da Liga Johto 
 Continua com as aventuras de Ash e seus amigos... 
 160-211 (lista) 
 NaN 
 
 
 5 
 NaN 
 NaN 
 Master Quest 
 Encerra as aventuras em Johto, Misty volta a C... 
 212-276 (lista) 
 NaN 
 
 
 6 
 Geração Avançada 
 Terceira 
 Pokémon: Avançado 
 Inicia as Aventuras de Ash, Brock,agora juntam... 
 277-316 (lista) 
 Hoenn 
 
 
 7 
 NaN 
 NaN 
 Desafio Avançado 
 Continua com a jornada de Ash e seus amigos em... 
 317-368 (lista) 
 NaN 
 
 
 8 
 NaN 
 NaN 
 Batalha Avançada 
 Encerra as aventuras em Hoenn e começa a Jorna... 
 369-421 (lista) 
 NaN 
 
 
 9 
 NaN 
 NaN 
 Batalha da Fronteira 
 Conclui a Jornada na Batalha da Fronteira. May... 
 422-468 (lista) 
 Kanto 
 
 
 10 
 Diamante e Pérola 
 Quarta 
 Diamante e Pérola 
 Inicia as aventuras de Ash e Brock em Sinnoh c... 
 469-520 (lista) 
 Sinnoh 
 
 
 11 
 NaN 
 NaN 
 Batalha Dimensional 
 Continua as aventuras de Ash, Brock e Dawn em ... 
 521-572 (lista) 
 NaN 
 
 
 12 
 NaN 
 NaN 
 Batalhas Galácticas 
 Continua a jornada de Ash, Dawn e Brock em Sin... 
 573-625 (lista) 
 NaN 
 
 
 13 
 NaN 
 NaN 
 Vencedores da Liga Sinnoh 
 Conclui a jornada de Ash, Dawn e Brock em Sinn... 
 626-659 (lista) 
 NaN 
 
 
 14 
 Preto e Branco 
 Quinta 
 Preto e Branco 
 Inicia as aventuras de Ash na região de Unova ... 
 660-707 (lista) 
 Unova 
 
 
 15 
 NaN 
 NaN 
 Destinos Rivais 
 Ash reencontra Dawn.Tem 49 episódios 
 708-756 (lista) 
 NaN 
 
 
 16 
 NaN 
 NaN 
 Aventuras em Unova (e Mais Além) 
 Continua a jornada de Ash, Iris e Cilan em Uno... 
 757-803 (lista) 
 NaN 
 
 
 17 
 XY 
 Sexta 
 A Série XY 
 Inicia as aventuras de Ash, Serena, Clemont e ... 
 804-852 (lista) 
 Kalos 
 
 
 18 
 NaN 
 NaN 
 Kalos Quest 
 Continua as aventuras de Ash, Serena, Clemont ... 
 853-897 (lista) 
 NaN 
 
 
 19 
 NaN 
 NaN 
 XY & Z 
 Continua A Saga de Ash ,Clement, Bonnie e Sere... 
 898-946 (lista) 
 NaN 
 
 
 20 
 Sun and Moon 
 Sétima 
 Sun and Moon 
 Inicia as aventuras de Ash, Lana, Mallow, Kiaw... 
 947- (Lista) 
 Alola

### Exercicio 7
O Jogo da Vida (The Game of Life) é um autômato celular (cellular automaton) introduzido por John Horton Conway em 1970. Um automato celular consiste de uma rede de células. Cada célula pode estar em um número finito de estados, como morta ou viva. O “jogo” é na verdade uma simulação que permite observar a evolução de um processo a partir de uma certa condição inicial.
O jogo se desenvolve sobre uma matriz bi-dimensional que pode ser tão grande quanto se queira. Vamos chamar essa matriz de mapa. Cada posição ou célula do mapa pode estar vazia (= célula morta) ou ocupada por um agente (= célula viva). Cada posição possui também até 8 posições vizinhas: imediatamente acima, abaixo, aos lados e nas diagonais. Em um determinado instante, o mapa contém uma geração de agentes. A geração no instante seguinte é determinada segundo as regras abaixo:
Novos agentes nascem em células vazias que possuam exatamente 3 agentes vizinhos;
Agentes com 2 ou 3 agentes vizinhos sobrevivem;
Agentes com menos de 2 agentes vizinhos morrem for falta de recursos;
Agentes com mais de 3 agentes vizinhos morrem por excesso de competição.


In [47]:
import numpy
def jogo(a):
    xmax, ymax = a.shape
    b = a.copy() 
    for x in range(xmax):
        for y in range(ymax):
            n = numpy.sum(a[max(x-1,0):min(x + 2, xmax),max(y-1, 0):min(y + 2, ymax)])-a[x, y]
            if a[x,y]:
                if n < 2 or n > 3:
                    b[x,y] = 0 
            elif n == 3 or n == 2:
                b[x, y] = 1 
    return(b)

vida = numpy.zeros((5, 5), dtype=numpy.byte)
vida[2, 1:4] = 1 
print(vida)
for i in range(3):
    vida= jogo(vida)
    print (vida)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 1 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
[[0 1 1 1 0]
 [0 1 1 1 0]
 [1 0 0 0 1]
 [0 1 1 1 0]
 [0 1 1 1 0]]
[[1 1 0 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 0 1 1]]


## Exercicio 8
Considere um conjunto de 10 triplets descrevendo 10 triângulos (com vértices compartilhados), encontrar o conjunto de segmentos de linha única compondo todos os triângulos

In [5]:
nao entendi o exercicio

SyntaxError: invalid syntax (<ipython-input-5-ea207c85a699>, line 1)