In [39]:
#Encontre índices de elementos não nulos de [1,2,0,0,4,0]

import numpy as np
v = np.array([1,2,0,0,4,0])
v!=0

array([ True,  True, False, False,  True, False], dtype=bool)

In [37]:
#Extrair a parte inteira de uma matriz aleatória

import numpy as np
import random 
a = random.randint(1,9)
b = random.randint(1,9)
print(a, b)
c= np.random.rand(a, b)*10
print(c)
c.astype(int)

(1, 8)
[[ 8.83193921  0.11566281  9.09279988  9.58936652  8.39334313  0.63475127
   8.27182577  1.75437066]]


array([[8, 0, 9, 9, 8, 0, 8, 1]])

In [28]:
#Considere uma matriz aleatória de 10×2 que represente coordenadas cartesianas, converta-as em coordenadas polares

import numpy as np
from numpy import linalg as LA
import math
from math import atan2
m = np.random.rand(10,2)*10
m = m.astype(int)
print("Coordenadas cartesianas:\n")
print(m)
print("\n")


x = list(m[:,0])
y = list(m[:,1])
print("Coordenadas polares:\n")
for i in range(len(m)):
    ro = (math.sqrt((pow(x[i], 2)) + (pow(y[i],2))))
    teta = math.atan2(y[i], x[i])
    xc = ro*math.cos(teta)
    yc = ro*math.sin(teta)
    print(xc, yc)
    
    






Coordenadas cartesianas:

[[6 4]
 [3 9]
 [5 0]
 [8 6]
 [5 5]
 [5 0]
 [6 9]
 [0 4]
 [8 8]
 [6 2]]


Coordenadas polares:

(6.0, 3.999999999999999)
(3.0, 9.0)
(5.0, 0.0)
(8.0, 6.0)
(5.000000000000001, 5.0)
(5.0, 0.0)
(6.000000000000001, 9.000000000000002)
(2.4492935982947064e-16, 4.0)
(8.000000000000002, 8.0)
(6.0, 2.0)


In [63]:
#Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos
import numpy as np
from numpy import linalg as LA
v = np.random.rand(100,2)*10
v = v.astype(int)
for i in range(len(v)):
    for j in range(1, len(v)):
        d = LA.norm(v[i]-v[j])
        print("Distancia entre"+str(v[i])+"e"+str(v[j])+"é igual a= "+str(d))

Distancia entre[2 1]e[7 0]é igual a= 5.09901951359
Distancia entre[2 1]e[6 8]é igual a= 8.0622577483
Distancia entre[2 1]e[9 7]é igual a= 9.21954445729
Distancia entre[2 1]e[0 9]é igual a= 8.24621125124
Distancia entre[2 1]e[8 1]é igual a= 6.0
Distancia entre[2 1]e[8 7]é igual a= 8.48528137424
Distancia entre[2 1]e[1 3]é igual a= 2.2360679775
Distancia entre[2 1]e[0 0]é igual a= 2.2360679775
Distancia entre[2 1]e[1 1]é igual a= 1.0
Distancia entre[2 1]e[1 2]é igual a= 1.41421356237
Distancia entre[2 1]e[7 9]é igual a= 9.43398113206
Distancia entre[2 1]e[5 4]é igual a= 4.24264068712
Distancia entre[2 1]e[5 3]é igual a= 3.60555127546
Distancia entre[2 1]e[2 3]é igual a= 2.0
Distancia entre[2 1]e[0 0]é igual a= 2.2360679775
Distancia entre[2 1]e[6 3]é igual a= 4.472135955
Distancia entre[2 1]e[9 0]é igual a= 7.07106781187
Distancia entre[2 1]e[4 4]é igual a= 3.60555127546
Distancia entre[2 1]e[5 1]é igual a= 3.0
Distancia entre[2 1]e[0 0]é igual a= 2.2360679775
Distancia entre[2 1]e[0 3]é

In [72]:
#Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?

import numpy as np


v = np.array([1, 2, 3, 4, 5])
lista=[]

for i in range(len(v)):
    a=0
    lista.append(v[i])
    while a<3:
        lista.append(0)
        a = a+1
print(lista)



[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
