In [1]:
#Exercicio 1
##Encontre índices de elementos não nulos de [1,2,0,0,4,0]
import numpy as np
matrix=[1,2,0,0,4,0]
for i in range(len(matrix)):
    if(matrix[i]!= 0):
        print(i)

0
1
4


In [5]:
#Exercicio 2
##Extrair a parte inteira de uma matriz aleatória.
import numpy as np
matrix=np.random.rand(3,4)
intmatrix=[]
for i in range(len(matrix)):
    aux=matrix[i]//1
    intmatrix.append(aux)
print(matrix)
print(intmatrix)

[[ 0.50142107  0.45872635  0.3831859   0.43066872]
 [ 0.9529897   0.65805558  0.55167795  0.84950445]
 [ 0.32862293  0.10917335  0.45742885  0.43463259]]
[array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.]), array([ 0.,  0.,  0.,  0.])]


In [6]:
#Exercicio3
##Considere uma matriz aleatória de 10x2 que represente coordenadas cartesianas, converta-as em coordenadas polares
import numpy as np
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)
matrix=np.random.rand(10,2)
matrix2pol=[]
for i in range(0,10):
    matrix2pol.append(cart2pol(matrix[i][0],matrix[i][1]))
print(matrix)        
print(matrix2pol)

[[ 0.51324874  0.48809033]
 [ 0.29542584  0.4664381 ]
 [ 0.7729903   0.4078156 ]
 [ 0.96180657  0.76233065]
 [ 0.43815117  0.8220024 ]
 [ 0.75987357  0.82616472]
 [ 0.02359055  0.87896559]
 [ 0.98458965  0.69318416]
 [ 0.71064125  0.64923675]
 [ 0.02795322  0.32592016]]
[(0.70827709164237351, 0.76027868831407674), (0.55212402130639482, 1.006203913724361), (0.87397228800090909, 0.48546878337322813), (1.2272815046513257, 0.67021419276739813), (0.93148504954369071, 1.0810759233368836), (1.1224776063332125, 0.82717053993172662), (0.87928210963997677, 1.5439637779740065), (1.2041266784442957, 0.61342792250423772), (0.96255874500387784, 0.74027439294452124), (0.32711669358483952, 1.4852386236894972)]


In [7]:
#Exercicio4
##Considere um vetor aleatório com forma (100,2) representando coordenadas, encontre as distâncias entre todos os pontos
import numpy as np
matrix=np.random.rand(10,2)
matrixD=[]
for i in range(len(matrix)):
    for j in range(len(matrix)):
        matrixD.append(np.sqrt(((matrix[i][0]-matrix[j][0])**2)+((matrix[i][0]-matrix[j][1])**2)))
print matrixD


[0.043905741380440122, 0.32702282802855542, 0.30177630132012773, 0.54351386222490461, 0.24659888371624211, 0.059922563126067044, 1.0194453779885251, 0.57817169308426464, 0.62400968123591771, 0.095682918417298979, 0.18682415538341413, 0.44165598637068115, 0.516496208589595, 0.70369431361064794, 0.40219278435995381, 0.26893898237083785, 1.2346457130615522, 0.73839930281260768, 0.83340542728084954, 0.14295555448432926, 0.36109857324441696, 0.38885766590643522, 0.0399738806721599, 0.41130080189995533, 0.29237531665103494, 0.27829426472851038, 0.6909270533476729, 0.43701623860266137, 0.31970135072022138, 0.4132149295846394, 0.038606120790478447, 0.34689572176134564, 0.3555681828536329, 0.58035028033086067, 0.27824835569800016, 0.11010451827026983, 1.0734178220679345, 0.61521044343305287, 0.67618229780714145, 0.057242195272131972, 0.37066149402604953, 0.39465137324522509, 0.047250272829322315, 0.41076697664366985, 0.29908302957982436, 0.28783863659585113, 0.68133812454240961, 0.4359429314641

In [9]:
#Exercicio5
##Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor?
vetor=[0,1,2,3,4,5]
vetor2=[]
for i in range(len(vetor)):
    vetor2.append(vetor[i])
    for i in range(0,3):
        vetor2.append(0)
print(vetor2)

[0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]
